@startuml com_api_stream_api_lola_runtime

' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' <https://www.apache.org/licenses/LICENSE-2.0>
'
' SPDX-License-Identifier: Apache-2.0

title Async Stream API in Lola Runtime

actor User
participant "Subscription" as Subscription
participant "SampleContainer" as SampleContainer
participant "Lola" as Lola

User -> Subscription: stream(new_samples, max_samples)
Subscription --> SampleContainer: Create with max_samples capacity

Note over Lola: Backend asynchronously\npushes samples in the SampleContainer

loop User polls the stream
    User -> Subscription: poll_next().await
    activate Subscription
    Subscription -> SampleContainer: Check samples >= 1

    alt Samples available
        Subscription --> User: Ready(Samples)
    else Waiting for Samples
        Subscription --> User: Pending
    end
    deactivate Subscription
end

Note over SampleContainer: Oldest samples dropped\nwhen buffer full

@enduml
