# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

filegroup(
    name = "offer_not_stopped_in_sd_fta",
    srcs = [
        "offer_not_stopped_in_sd_fta.puml",
    ],
    visibility = ["//score/mw/com/dependability:__subpackages__"],
)

filegroup(
    name = "offer_stopped_for_wrong_instance_in_sd_fta",
    srcs = [
        "offer_stopped_for_wrong_instance_in_sd_fta.puml",
    ],
    visibility = ["//score/mw/com/dependability:__subpackages__"],
)

filegroup(
    name = "shm_objects_unlink_failure_fta",
    srcs = [
        "shm_objects_unlink_failure_fta.puml",
    ],
    visibility = ["//score/mw/com/dependability:__subpackages__"],
)

filegroup(
    name = "stop_offer_state_inconsistent_fta",
    srcs = [
        "stop_offer_state_inconsistent_fta.puml",
    ],
    visibility = ["//score/mw/com/dependability:__subpackages__"],
)
