# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@score_tooling//bazel/rules/rules_score:rules_score.bzl", "unit_design")

unit_design(
    name = "managed_memory_resource_unit_design",
    visibility = ["//score/memory:__pkg__"],
)

unit_design(
    name = "shared_memory_resource_unit_design",
    visibility = ["//score/memory:__pkg__"],
)

unit_design(
    name = "shared_memory_factory_unit_design",
    visibility = ["//score/memory:__pkg__"],
)

unit_design(
    name = "memory_resource_registry_unit_design",
    visibility = ["//score/memory:__pkg__"],
)

unit_design(
    name = "offset_ptr_unit_design",
    visibility = ["//score/memory:__pkg__"],
)

unit_design(
    name = "polymorphic_offset_ptr_allocator_unit_design",
    visibility = ["//score/memory:__pkg__"],
)

unit_design(
    name = "containers_unit_design",
    visibility = ["//score/memory:__pkg__"],
)

unit_design(
    name = "flock_mutex_unit_design",
    visibility = ["//score/memory:__pkg__"],
)

unit_design(
    name = "typed_memory_unit_design",
    visibility = ["//score/memory:__pkg__"],
)

unit_design(
    name = "sealed_shared_memory_unit_design",
    visibility = ["//score/memory:__pkg__"],
)
