' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

namespace score::memory::shared {

class "PolymorphicOffsetPtrAllocator<T>" as PolymorphicOffsetPtrAllocator

class "Vector<T>" as Vector {
  +alias : std::vector<T, std::scoped_allocator_adaptor<PolymorphicOffsetPtrAllocator<T>>>
}

class "Map<K, V, Comp>" as Map {
  +allocator_type : PolymorphicOffsetPtrAllocator<value_type>
  +linux_impl : boost::interprocess::map
  +other_impl : std::map
}

class "BasicString<CharT, Traits>" as BasicString {
  +alias : std::basic_string<CharT, Traits, PolymorphicOffsetPtrAllocator<CharT>>
}

class String {
  +alias : BasicString<char>
}

Vector ..> PolymorphicOffsetPtrAllocator : scoped allocator adaptor
Map ..> PolymorphicOffsetPtrAllocator : linux=boost::interprocess, else=std::map
BasicString ..> PolymorphicOffsetPtrAllocator : allocator
String ..> BasicString

}

@enduml
