' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

namespace score::memory::shared {

abstract class ManagedMemoryResource {
  +construct(args): T*
  +destruct(t): void
  {abstract} +getBaseAddress(): void*
  {abstract} +getUsableBaseAddress(): void*
  {abstract} +GetUserAllocatedBytes(): std::size_t
  +IsOffsetPtrBoundsCheckBypassingEnabled(): bool
  {abstract} -getEndAddress(): const void*
  {abstract} -getMemoryResourceProxy(): const MemoryResourceProxy*
}

class NewDeleteDelegateMemoryResource {
  +NewDeleteDelegateMemoryResource(mem_res_id, upstream_resource)
  +~NewDeleteDelegateMemoryResource()
  +getMemoryResourceProxy(): const MemoryResourceProxy*
  +getBaseAddress(): void*
  +getUsableBaseAddress(): void*
  +GetUserAllocatedBytes(): std::size_t
  +IsOffsetPtrBoundsCheckBypassingEnabled(): bool
  -do_allocate(bytes, alignment): void*
  -do_deallocate(p, bytes, alignment): void
  -do_is_equal(other): bool
  -getEndAddress(): const void*
  --
  -upstream_resource_ : score::cpp::pmr::memory_resource*
  -memory_resource_id_ : std::uint64_t
  -proxy_ : score::memory::shared::MemoryResourceProxy
  -sum_allocated_bytes_ : std::size_t
  -current_upstream_allocations_ : std::map<void*, AllocateInfo>
}

class "NewDeleteDelegateMemoryResource::AllocateInfo" as AllocateInfo {
  +AllocateInfo(bytes, alignment)
  --
  +bytes : std::size_t
  +alignment : std::size_t
}

class MemoryResourceProxy
class SharedMemoryResource

ManagedMemoryResource <|-- NewDeleteDelegateMemoryResource
ManagedMemoryResource <|-- SharedMemoryResource
NewDeleteDelegateMemoryResource *-- AllocateInfo
NewDeleteDelegateMemoryResource *-- MemoryResourceProxy

}

@enduml
