' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

component "MemoryResourceRegistry" as memory_resource_registry
component "MemoryRegionMapImpl<AtomicIndirectorType>" as memory_region_map
component "MemoryRegionBounds" as memory_region_bounds
component "ManagedMemoryResource" as managed_memory_resource

memory_resource_registry --> memory_region_map
memory_resource_registry --> managed_memory_resource
memory_region_map --> memory_region_bounds

@enduml
