' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

namespace score::memory::shared {

class OffsetPtr {
  +OffsetPtr(ptr)
  +OffsetPtr(other)
  {static} +pointer_to(ref): OffsetPtr
  +operator*(): reference
  +operator[](idx): reference
  +operator+=(offset): OffsetPtr&
  +operator-=(offset): OffsetPtr&
  +get(): pointer
  +operator->(): pointer
  +operator!(): bool
  {static} -CopyFrom(source_offset_ptr, target_offset_ptr): std::pair<difference_type, MemoryRegionBounds>
  {static} -GetPointerWithBoundsCheck(offset_ptr_address, offset, offset_ptr_memory_bounds_when_not_in_shm, pointed_type_size): pointer
  {static} -GetPointerWithoutBoundsCheck(offset_ptr_address, offset): pointer
  -IncrementOffset(multiple_of_pointed_type_to_increment): void
  -DecrementOffset(multiple_of_pointed_type_to_decrement): void
  {static} -CalculateOffsetFromPointer(offset_ptr_address, pointed_to_address): difference_type
  {static} -CalculatePointerFromOffset(offset, offset_ptr): pointer
  --
  -offset_ : detail_offset_ptr::difference_type
  -memory_bounds_ : MemoryRegionBounds
}

class MemoryRegionBounds
class MemoryResourceRegistry

OffsetPtr *-- MemoryRegionBounds
OffsetPtr ..> MemoryResourceRegistry

' OffsetPtr relies on the free functions declared in offset_ptr_bounds_check.h
' and pointer_arithmetic_util.h for bounds validation and pointer arithmetic.

}

@enduml
