' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

title PolymorphicOffsetPtrAllocator<T>::allocate chooses proxy or heap fallback

start
if (proxy_ != nullptr?) then (yes)
  :number_bytes_to_allocate = size * sizeof(T);
  :proxy_->allocate(number_bytes_to_allocate, alignof(T));
  :return OffsetPtr<T>{allocatedMemory};
else (no)
  :number_bytes_to_allocate = size * sizeof(T);
  :std::malloc(number_bytes_to_allocate);
  :return OffsetPtr<T>{allocatedMemory};
endif
stop

@enduml
