@startuml

namespace mw_com {
  namespace lola_binding {

    interface "LolaSkeletonForLolaSkeletonEventInterface" as lola_skeleton_for_lola_skeleton_event_interface <<interface>> {
      Register()
      DisconnectQmConsumer()
    }

    interface "LolaSkeletonForLolaSkeletonMethodInterface" as lola_skeleton_for_lola_skeleton_method_interface <<interface>> {
      RegisterMethod()
    }

    ' lola::SkeletonEvent interfaces
    interface "LolaGenericSkeletonEventForImplSkeletonEventInterface" as lola_generic_skeleton_event_for_impl_skeleton_event_interface <<interface>> {
      Send()
      Allocate()
      PrepareOffer()
      PrepareStopOffer()
    }

    ' lola::SkeletonMethod interfaces
    interface "LolaSkeletonMethodForLolaSkeletonInterface" as lola_skeleton_method_for_lola_skeleton_interface <<interface>> {
      OnProxyMethodSubscribeFinished()
      OnProxyMethodUnsubscribeFinished()
      IsRegistered()
      UnregisterMethodCallHandlers()
    }
  }
}

@enduml