# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@score_tooling//bazel/rules/rules_score:rules_score.bzl", "unit_design")

unit_design(
    name = "service_discovery_protocol_unit_design",
    visibility = ["//score/mw/com/service_discovery:__pkg__"],
)

unit_design(
    name = "service_discovery_registry_unit_design",
    visibility = ["//score/mw/com/service_discovery:__pkg__"],
)

unit_design(
    name = "service_discovery_daemon_unit_design",
    visibility = ["//score/mw/com/service_discovery:__pkg__"],
)

unit_design(
    name = "service_discovery_message_passing_client_unit_design",
    visibility = ["//score/mw/com/service_discovery:__pkg__"],
)

unit_design(
    name = "service_discovery_message_passing_server_unit_design",
    visibility = ["//score/mw/com/service_discovery:__pkg__"],
)
