' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************
@startuml

namespace score::memory::shared {
  class "SharedMemoryFactoryMock" {
    +Open(const std::string&, bool, const std::optional<score::cpp::span<const uid_t>>&): std::shared_ptr<ISharedMemoryResource>
    +Create(std::string, InitializeCallback, std::size_t, const UserPermissions&, bool): std::shared_ptr<ISharedMemoryResource>
    +CreateAnonymous(std::uint64_t, InitializeCallback, std::size_t, const UserPermissions&, bool): std::shared_ptr<ISharedMemoryResource>
    +CreateOrOpen(std::string, InitializeCallback, std::size_t, AccessControl, bool): std::shared_ptr<ISharedMemoryResource>
    +Remove(const std::string&): void
    +RemoveStaleArtefacts(const std::string&): void
    +SetTypedMemoryProvider(std::shared_ptr<score::memory::shared::TypedMemory>): void
    +SetInterVMMemoryProvider(std::shared_ptr<score::memory::shared::TypedMemory>): void
    +GetControlBlockSize(): std::size_t
    +Clear(): void
  }

  class "SharedMemoryResourceHeapAllocatorMock" {
    +SharedMemoryResourceHeapAllocatorMock(std::uint64_t)
    +getBaseAddress(): void*
    +getUsableBaseAddress(): void*
    +getEndAddress(): const void*
    +getPath(): const std::string*
    +UnlinkFilesystemEntry(): void
    +GetFileDescriptor(): std::int32_t
    +IsShmInTypedMemory(): bool
    +IsOffsetPtrBoundsCheckBypassingEnabled(): bool
    +GetIdentifier(): std::string_view
    +getMemoryResourceProxy(): const MemoryResourceProxy*
    +GetUserAllocatedBytes(): std::size_t
  }

  class "SharedMemoryResourceMock" {
    +getMemoryResourceProxy(): MemoryResourceProxy*
    +getBaseAddress(): void*
    +getUsableBaseAddress(): void*
    +getEndAddress(): const void*
    +getPath(): const std::string*
    +UnlinkFilesystemEntry(): void
    +GetFileDescriptor(): std::int32_t
    +IsShmInTypedMemory(): bool
    +do_allocate(const std::size_t, const std::size_t): void*
    +do_deallocate(void*, std::size_t, std::size_t): void
    +do_is_equal(const score::cpp::pmr::memory_resource&): bool
    +GetUserAllocatedBytes(): std::size_t
    +IsOffsetPtrBoundsCheckBypassingEnabled(): bool
    +GetIdentifier(): std::string_view
  }

  class "MyBoundedMemoryResource" {
    +MyBoundedMemoryResource(std::size_t, bool)
    +MyBoundedMemoryResource(const std::pair<void*, void*>&, bool)
    +getMemoryResourceProxy(): MemoryResourceProxy*
    +getBaseAddress(): void*
    +getUsableBaseAddress(): void*
    +getEndAddress(): const void*
    +getAllocatedMemory(): size_t
    +GetUserAllocatedBytes(): std::size_t
    +GetUserDeAllocatedBytes(): std::size_t
    +IsOffsetPtrBoundsCheckBypassingEnabled(): bool
    +getMemoryResourceId(): std::uint64_t
  }

  class "MyBoundedSharedMemoryResource" {
    +MyBoundedSharedMemoryResource(std::size_t, bool)
    +MyBoundedSharedMemoryResource(const std::pair<void*, void*>&, bool)
    +getPath(): const std::string*
    +GetIdentifier(): std::string_view
    +UnlinkFilesystemEntry(): void
    +GetFileDescriptor(): FileDescriptor
    +IsShmInTypedMemory(): bool
    +getMemoryResourceProxy(): MemoryResourceProxy*
    +getBaseAddress(): void*
    +getUsableBaseAddress(): void*
    +getEndAddress(): const void*
    +getAllocatedMemory(): size_t
    +GetUserAllocatedBytes(): std::size_t
    +GetUserDeAllocatedBytes(): std::size_t
    +IsOffsetPtrBoundsCheckBypassingEnabled(): bool
    +getMemoryResourceId(): std::uint64_t
  }

  class "MyMemoryResource" {
    +MyMemoryResource(const std::pair<std::uintptr_t, std::uintptr_t>&)
    +getMemoryResourceProxy(): MemoryResourceProxy*
    +getBaseAddress(): void*
    +getUsableBaseAddress(): void*
    +GetUserAllocatedBytes(): std::size_t
    +getEndAddress(): const void*
    +IsOffsetPtrBoundsCheckBypassingEnabled(): bool
    +getAllocatedMemory(): size_t
    +getMemoryResourceId(): std::uint64_t
    +isAllocationPossible(): bool
    +setAllocationPossible(bool): void
  }

  ' This is currently used by mw/com. We should either move it to mw/com so it's not publicly exposed here (for production use) 
  ' or remove the simulation mode in mw/com so it's no longer needed (Ticket 285871)
  class "NewDeleteDelegateMemoryResource" {
    +NewDeleteDelegateMemoryResource(std::uint64_t, score::cpp::pmr::memory_resource*)
    +getMemoryResourceProxy(): const MemoryResourceProxy*
    +getBaseAddress(): void*
    +getUsableBaseAddress(): void*
    +GetUserAllocatedBytes(): std::size_t
    +IsOffsetPtrBoundsCheckBypassingEnabled(): bool
  }
}

@enduml
