@startuml safety_sentinel_mwcom_design
title "lola_to_impl_skeleton_interfaces"

package "Binding Independent" as binding_independent <<component>>  #F9E7A8 {
  package "impl::Skeleton" as skeleton <<component>>  {
    component "impl::Skeleton" as impl_skeleton <<unit>> 
    component "impl::SkeletonEvent" as impl_skeleton_event <<unit>> 
    component "impl::SkeletonMethod" as impl_skeleton_method <<unit>> 
    component "impl::SkeletonField" as impl_skeleton_field <<unit>> 
  }
}

package "Lola" as lola_binding <<component>>  #DDECD2 {
  package "lola::Skeleton" as lola_skeleton_component <<component>>  {
    component "lola::Skeleton" as lola_skeleton <<unit>> 
    component "lola::SkeletonEvent" as lola_skeleton_event <<unit>> 
    component "lola::SkeletonMethod" as lola_skeleton_method <<unit>> 
  }
}

''' lola::Skeleton interfaces
' lola::Skeleton interfaces
interface "LolaSkeletonForImplSkeletonInterface" as lola_skeleton_for_impl_skeleton_interface <<interface>>
impl_skeleton --( lola_skeleton_for_impl_skeleton_interface
lola_skeleton -- lola_skeleton_for_impl_skeleton_interface

' lola::SkeletonEvent interfaces
interface "LolaSkeletonEventForImplSkeletonEventInterface" as lola_skeleton_event_for_impl_skeleton_event_interface <<interface>>
impl_skeleton_event --( lola_skeleton_event_for_impl_skeleton_event_interface
lola_skeleton_event -- lola_skeleton_event_for_impl_skeleton_event_interface

' lola::SkeletonMethod interfaces
interface "LolaSkeletonMethodForImplSkeletonMethodInterface" as lola_skeleton_method_for_impl_skeleton_method_interface <<interface>>
impl_skeleton_method --( lola_skeleton_method_for_impl_skeleton_method_interface
lola_skeleton_method -- lola_skeleton_method_for_impl_skeleton_method_interface

@enduml
