' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

autonumber "<b>[00]"
skinparam stereotypePosition bottom

actor "User Application" as UA
participant "Proxy::instance" as PROXY
participant "OS::RAMFS" as OSRAMFS_methods <<dev/shmem>>

activate UA
UA -> PROXY ++: Create ServiceProxy(FindServiceHandle)

note right of OSRAMFS_methods
    multiple proxy instances
    due to Security and FFI
end note

loop for each proxy instance
    PROXY -> OSRAMFS_methods ++: Check/Create Folder and File Structure
    OSRAMFS_methods --> PROXY --

    PROXY -> OSRAMFS_methods ++: Lock File and set Permissions
    OSRAMFS_methods --> PROXY --
end

PROXY -> UA --: Handle <Proxy Instance>

@enduml
