cc_library(
    name = "test_method_datatype",
    srcs = ["test_method_datatype.cpp"],
    hdrs = ["test_method_datatype.h"],
    visibility = ["//score/mw/com/test/partial_restart/methods:__subpackages__"],
    deps = [
        "//score/mw/com",
    ],
)
