' *******************************************************************************
' Copyright (c) {year} Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

!include fta_metamodel.puml

$FailureMode("Skeleton Not offered", "Communication.ServiceNotOffered")

$OrGate("Gate1", "Communication.ServiceNotOffered")
$IntermediateEvent("Service Discovery Marker files have been incorrectly created", "Event4", "Gate1")
$OrGate("Gate4", "Event4")
$RootCause("Not created at all", "NotCreatedAtAll", "Gate4")
$RootCause("Wrong Directory Structure", "WrongDirectoryStructure", "Gate4")
$RootCause("Wrong Marker File name", "WrongMarkerFileName", "Gate4")
$IntermediateEvent("Shared Memory segment was not created", "Event2", "Gate1")
$OrGate("Gate3", "Event2")
$RootCause("Shared Memory segment does not try to create segment.", "SharedMemorySegmentDoesNotTryToCreateSegment", "Gate3")
$RootCause("OS related functionality failed", "OsRelatedFunctionalityFailed", "Gate3")
$RootCause("Shared Memory segments are created under wrong name", "SharedMemorySegmentsAreCreatedUnderWrongName", "Gate1")
$IntermediateEvent("Instance Specifier is wrongly configured", "Event1", "Gate1")
$OrGate("Gate2", "Event1")
$RootCause("Instance Specifier resolution broken", "InstanceSpecifierResolutionBrokenNotOffered", "Gate2")
$RootCause("Differently configured between skleton and proxy side", "DifferentlyConfiguredBetweenSkletonAndProxySide", "Gate2")
$IntermediateEvent("Wrongly configured on Skeleton / Proxy side", "Event8", "Gate2")
$IntermediateEvent("Defect configuration", "Event13", "Event8")
$TransferInGate("Transfer1", "Event13")

@enduml
