# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Problem Report
description: Issue to track a bug
title: "Bug: Your bugfix title"
labels: ["codeowner_review"]
body:
- type: markdown
  attributes:
    value: "## <ins>Bug Ticket creation</ins>"
- type: textarea
  attributes:
    label: Description
    description: Short Description of the Bug
  validations:
    required: true
- type: textarea
  attributes:
    label: Supporting Information
    description: |
      During which operational state did the issue occur
      Observations / Screenshots / Traces
  validations:
    required: false
- type: dropdown
  attributes:
    label: Classification
    options:
      - minor
      - major
      - critical
      - blocker
    default: 0
  validations:
    required: true
- type: dropdown
  attributes:
    label: Affected Version
    options:
      - 0.5
      - 1.0
    default: 0
  validations:
    required: true
- type: dropdown
  attributes:
    label: Expected Closure Version
    options:
      - 0.5
      - 1.0
    default: 0
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Category
    options:
      - label: Safety Related
      - label: Security Related
