' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

!include fta_metamodel.puml

$FailureMode("Wrong service found", "Communication.WrongServiceFound")

$OrGate("Gate1", "Communication.WrongServiceFound")
$IntermediateEvent("Service is offered under wrong IDs", "Event2", "Gate1")
$TransferInGate("Transfer2", "Event2")
$IntermediateEvent("Wrong service discovery marker file searched for", "Event3", "Gate1")
$OrGate("Gate2", "Event3")
$RootCause("Wrong path resolved from InstanceIdentifier", "WrongPathResolvedFromInstanceidentifier", "Gate2")
$RootCause("InstanceSpecifier resolved to wrong InstanceIdentifier", "InstancespecifierResolvedToWrongInstanceidentifier", "Gate2")
$IntermediateEvent("Wrongly configured", "Event1", "Gate1")
$TransferInGate("Transfer1", "Event1")

@enduml
