' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

!include fta_metamodel.puml

$FailureMode("Service is found, but does not exist", "Communication.ServiceIsFoundButDoesNotExist")

$OrGate("Gate1", "Communication.ServiceIsFoundButDoesNotExist")
$RootCause("Service was offered, but not unliked on stop offer", "ServiceWasOfferedButNotUnlikedOnStopOffer", "Gate1")
$RootCause("Shared Memory is opened eventhough file does not exist", "SharedMemoryIsOpenedEventhoughFileDoesNotExist", "Gate1")
$IntermediateEvent("Shared Memory Object exists but not accessable", "Event3", "Gate1")
$OrGate("Gate2", "Event3")
$RootCause("Wrong Provider", "WrongProvider", "Gate2")
$RootCause("Wrong Name", "WrongName", "Gate2")
$RootCause("Wrong ACL", "WrongAcl", "Gate2")
$RootCause("Shared Memory Object does not exist", "SharedMemoryObjectDoesNotExist", "Gate1")

@enduml
