# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# DEPRECATED: This target has been moved to //score/mw/com/rust:api
# This alias is provided for backward compatibility.
# Please update your dependencies to use the new location.
alias(
    name = "com-api",
    actual = "//score/mw/com/rust:api",
    deprecation = "Use //score/mw/com/rust:api instead. This target will be removed before v1.0 release.",
    visibility = ["//visibility:public"],
)
