' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

!include fta_metamodel.puml

$FailureMode("Wrong input arguments used", "Communication.WrongMethodInArgsUsed")

$OrGate("Gate1", "Communication.WrongMethodInArgsUsed")
$IntermediateEvent("Callee used wrong InArgs", "Event1", "Gate1")
$IntermediateEvent("Callee used corrupted InArgs", "Event2", "Gate1")
$OrGate("Gate2", "Event1")
$OrGate("Gate3", "Event2")
$RootCause("Callee used InArgs from wrong location", "CalleeUsedInArgsFromWrongLocation", "Gate2")
$RootCause("Callee used InArgs before being provided", "CalleeUsedInArgsBeforeBeingProvided", "Gate2")

$RootCause("Callee used InArgs in wrong layout", "CalleeUsedInArgsInWrongLayout", "Gate3")
$RootCause("Callee used InArgs while concurrently updated", "CalleeUsedInArgsWhileConcurrentlyUpdated", "Gate3")
$RootCause("InArgs corrupted by 3d party", "InArgsCorruptedBy3rdParty", "Gate3")

@enduml
