@startuml safety_sentinel_mwcom_design
title "lola_to_impl_skeleton_interfaces"

package "Binding Independent" as binding_independent <<component>> {
  package "SkeletonAndServiceElements" as skeleton_and_service_elements <<component>> {
    component "Skeleton" as impl_skeleton <<unit>> 
    component "SkeletonEvent" as impl_skeleton_event <<unit>> 
    component "SkeletonMethod" as impl_skeleton_method <<unit>> 
    component "SkeletonField" as impl_skeleton_field <<unit>> 
  }
}

package "Lola Binding" as lola_binding  <<component>> {
  package "SkeletonAndServiceElements" as lola_skeleton_and_service_elements <<component>> {
    component "Skeleton" as lola_skeleton <<unit>> 
    component "SkeletonEvent" as lola_skeleton_event <<unit>> 
    component "SkeletonMethod" as lola_skeleton_method <<unit>> 
  }
}

''' lola::Skeleton interfaces
' lola::Skeleton interfaces
interface "LolaSkeletonForImplSkeletonInterface" as lola_skeleton_for_impl_skeleton_interface <<interface>>
impl_skeleton --( lola_skeleton_for_impl_skeleton_interface
lola_skeleton -- lola_skeleton_for_impl_skeleton_interface

' lola::SkeletonEvent interfaces
interface "LolaSkeletonEventForImplSkeletonEventInterface" as lola_skeleton_event_for_impl_skeleton_event_interface <<interface>>
impl_skeleton_event --( lola_skeleton_event_for_impl_skeleton_event_interface
lola_skeleton_event -- lola_skeleton_event_for_impl_skeleton_event_interface

' lola::SkeletonMethod interfaces
interface "LolaSkeletonMethodForImplSkeletonMethodInterface" as lola_skeleton_method_for_impl_skeleton_method_interface <<interface>>
impl_skeleton_method --( lola_skeleton_method_for_impl_skeleton_method_interface
lola_skeleton_method -- lola_skeleton_method_for_impl_skeleton_method_interface

@enduml
