/********************************************************************************
 * Copyright (c) 2025 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-License-Identifier: Apache-2.0
 ********************************************************************************/
/// Type-state marker for uninitialized field value state (compile-time tracking).
///
/// These marker types are never constructed as values - they only appear as generic
/// type parameters inside `PhantomData<(S, H)>` on the generated `{Id}Validator` struct
/// (see `TypeStateValidator` in `score_com_macros`). The compiler's `dead_code` lint
/// flags unit structs that are never instantiated, so it is suppressed here deliberately.
#[allow(dead_code)]
pub struct Uninit;

/// Type-state marker for initialized field value state (compile-time tracking).
/// See [`Uninit`] for why `dead_code` is suppressed.
#[allow(dead_code)]
pub struct Init;

/// Type-state marker for handler not registered (compile-time tracking).
/// See [`Uninit`] for why `dead_code` is suppressed.
#[allow(dead_code)]
pub struct HandlerNotSet;

/// Type-state marker for handler registered (compile-time tracking).
/// See [`Uninit`] for why `dead_code` is suppressed.
#[allow(dead_code)]
pub struct HandlerSet;

/// Field capability tag: by adding this on interface macro, consumer can call async `get_*()` on this field.
/// Use in `Field<T, WithGetter>` (or combined: `Field<T, WithGetter + WithSetter + WithNotifier>`).
/// See [`Uninit`] for why `dead_code` is suppressed.
#[allow(dead_code)]
pub struct WithGetter;

/// Field capability tag: by adding this on interface macro, consumer can call async `set_*()` on this field.
/// Use in `Field<T, WithSetter>` (or combined: `Field<T, WithGetter + WithSetter + WithNotifier>`).
/// See [`Uninit`] for why `dead_code` is suppressed.
#[allow(dead_code)]
pub struct WithSetter;

/// Field capability tag: by adding this on interface macro, consumer can `subscribe()` to field-value-change notifications.
/// Use in `Field<T, WithNotifier>` (or combined: `Field<T, WithGetter + WithSetter + WithNotifier>`).
/// See [`Uninit`] for why `dead_code` is suppressed.
#[allow(dead_code)]
pub struct WithNotifier;

/// Main interface macro that generates Consumer, Producer, and OfferedProducer types
/// along with all necessary trait implementations.
///
/// Supports Event-only interfaces (backward compatible) and mixed interfaces containing
/// any combination of `Event<T>`, `Field<T>`, and `method_name(Args) -> Return` members
/// in the same definition block.
///
/// Automatically generates unique type names from the identifier of macro invocation.
/// For an interface with identifier `{id}`, it generates:
/// - `{id}Interface` - Struct representing the interface with INTERFACE_ID constant
/// - `{id}Consumer<R>` - Consumer implementation with event subscribers, field subscribers,
///   and method callers
/// - `{id}Producer<R>` - Producer implementation
/// - `{id}OfferedProducer<R>` - Offered producer implementation with event publishers,
///   field publishers, and method handlers
/// - Implements the `Interface`, `Consumer`, `Producer`, and `OfferedProducer` traits
///   for the respective types.
/// - `Interface_ID` is generated by default as the module path + interface name,
///   but can be overridden by providing a custom UID as a second parameter to the macro.
///
/// # Member types
/// - `name: Event<T>` - event subscriber / publisher pair
/// - `name: Field<T>` - field subscriber / publisher pair (with set-handler callback support)
/// - `name(Args) -> Return` - method caller / handler pair (fn-like syntax)
///
/// # Parameters
/// - Keywords: `interface` followed by the interface identifier and a block of member definitions.
/// - `$id`: Simple identifier used for type name generation (e.g., Vehicle, Engine)
/// - Members can be any mix of `Event<T>`, `Field<T>`, and `name(Args) -> Return`
///
/// # Example: Event-only with auto-generated ID
/// ```ignore
/// mod abc {
///     use score_com::interface;
///     interface!(
///         interface Vehicle {
///             left_tire: Event<Tire>,
///             exhaust: Event<Exhaust>,
///         }
///     );
/// }
/// ```
/// The generated code will include:
/// - `VehicleInterface` struct with `INTERFACE_ID = "abc::Vehicle"`
/// - `VehicleConsumer<R>` struct that implements `Consumer` trait for subscribing to
///   "left_tire" and "exhaust" events.
/// - `VehicleProducer<R>` struct that implements `Producer` trait for producing
///   "left_tire" and "exhaust" events.
/// - `VehicleOfferedProducer<R>` struct that implements `OfferedProducer` trait for offering
///   "left_tire" and "exhaust" events.
/// - `VehicleConsumer<R>`, `VehicleProducer<R>`, `VehicleOfferedProducer<R>`
///
/// # Example: Mixed interface (Event + Field + Method) with custom ID
/// ```ignore
/// mod abc {
///     use score_com::interface;
///     interface!(
///         interface Vehicle {
///             Id = "AbcInterface",
///             left_tire: Event<Tire>,
///             left_tire_field: Field<Tire, WithGetter + WithSetter + WithNotifier>,
///             left_tire_method(Tire) -> Tire,
///         }
///     );
/// }
/// ```
/// Here Id is explicitly set to "AbcInterface" instead of the default "abc::Vehicle".
/// The generated code will include:
/// - `VehicleInterface` struct with `INTERFACE_ID = "AbcInterface"`
/// - `VehicleConsumer<R>` with `left_tire: Subscriber<Tire>`, `left_tire_field: FieldSubscriber<Exhaust>`,
///   `left_tire_method: MethodCaller<(Tire,), Tire>` and a convenience `left_tire_method(arg0: Tire)` method.
/// - `VehicleProducer<R>` (derives `TypeStateValidator`) with `left_tire_field: FieldPublisher<Exhaust>`,
///   `left_tire_method: MethodHandler<(Tire,), Tire>`. Requires `.init()` chain before `.offer()`.
/// - `VehicleOfferedProducer<R>` with event publisher `left_tire`, plus moved field publisher and
///   method handler.
/// - For `left_tire_field`, the user needs to both update the initial value and register the
///   set-handler callback, using the same `init()` chain, before offering the producer instance.
///
/// The code will look like this:
/// ```ignore
/// let producer = producer_builder.build().expect("Failed to build producer instance");
/// producer.init()
///     .update_left_tire_field(&initial_value)?
///     .register_set_handler_left_tire_field(|value| {
///         println!("Received left_tire_field update: {:?}", value);
///     })
///     .register_left_tire_method_handler(|tire: Tire| {
///         println!("Received left_tire_method call with tire: {:?}", tire);
///         tire
///     })
///     .offer()?;
/// ```
/// In the code above, if the user forgets to register the field set-handler or the method
/// handler, it will be a compile-time error, since `init()` requires all handlers to be
/// registered before `offer()` becomes available.
///
/// If the user calls `producer.offer()` directly (without going through `init()`), it will
/// panic at runtime, since the handlers have not been registered yet.
#[macro_export]
macro_rules! interface {
    // Default unique ID based on the module path and interface name
    (interface $id:ident { $($event_name:ident : Event<$event_type:ty>),+ $(,)? }) => {
        $crate::interface_common!($id);
        $crate::interface_consumer!($id, $($event_name, Event<$event_type>),+);
        $crate::interface_producer!($id, $($event_name, Event<$event_type>),+);
    };

    // Custom unique Id provided by the user
    (interface $id:ident {
        Id = $uid:expr,
        $($event_name:ident : Event<$event_type:ty>),+ $(,)?
    }) => {
        $crate::interface_common!($id, $uid);
        $crate::interface_consumer!($id, $($event_name, Event<$event_type>),+);
        $crate::interface_producer!($id, $($event_name, Event<$event_type>),+);
    };

    // This is for backward compatibility for existing users with comma (,)
    (interface $id:ident, {
        Id = $uid:expr,
        $($event_name:ident : Event<$event_type:ty>),+ $(,)?
    }) => {
        $crate::interface! {
            interface $id {
                Id = $uid,
                $($event_name : Event<$event_type>),+
            }
        }
    };

    // Mixed / unified: custom ID
    (interface $id:ident {
        Id = $uid:expr,
        $($members:tt)*
    }) => {
        $crate::interface_common!($id, $uid);
        $crate::_interface_collect_members!(
            @id[$id, $uid]
            @ev[]
            @fi[]
            @fi_n[]
            @fi_g[]
            @fi_s[]
            @me[]
            $($members)*
        );
    };

    // Mixed / unified: auto-generated ID
    (interface $id:ident { $($members:tt)* }) => {
        $crate::interface_common!($id);
        $crate::_interface_collect_members!(
            @id[$id, concat!(module_path!(), "::", stringify!($id))]
            @ev[]
            @fi[]
            @fi_n[]
            @fi_g[]
            @fi_s[]
            @me[]
            $($members)*
        );
    };
}

/// Helper for `_interface_collect_members!`.
///
/// Iterates over the tag list of a single field, adding the field to the correct per-tag
/// accumulator list. When all tags are consumed, calls back to `_interface_collect_members!`
/// with the updated lists and the remaining interface members.
#[doc(hidden)]
#[macro_export]
macro_rules! _field_split_tags {
    // Base: all tags consumed - call back to _interface_collect_members! with updated lists
    (
        @ctx[
            @id[$id:ident, $uid:expr]
            @ev[$($ev_name:ident : $ev_type:ty ,)*]
            @fi[$($fi_name:ident : $fi_type:ty ,)*]
            @me[$($me_name:ident [$($me_arg_ty:ty),*] -> $me_ret:ty ,)*]
            @rest[$($rest:tt)*]
        ]
        @fi_n[$($fin_name:ident : $fin_type:ty ,)*]
        @fi_g[$($fig_name:ident : $fig_type:ty ,)*]
        @fi_s[$($fis_name:ident : $fis_type:ty ,)*]
        @field[$_name:ident : $_t:ty]
        @tags[]
    ) => {
        $crate::_interface_collect_members!(
            @id[$id, $uid]
            @ev[$($ev_name : $ev_type ,)*]
            @fi[$($fi_name : $fi_type ,)*]
            @fi_n[$($fin_name : $fin_type ,)*]
            @fi_g[$($fig_name : $fig_type ,)*]
            @fi_s[$($fis_name : $fis_type ,)*]
            @me[$($me_name [$($me_arg_ty),*] -> $me_ret ,)*]
            $($rest)*
        );
    };

    // WithNotifier: add field to fi_n list, recurse with remaining tags
    (
        @ctx[$($ctx:tt)*]
        @fi_n[$($fin_name:ident : $fin_type:ty ,)*]
        @fi_g[$($fi_g:tt)*]
        @fi_s[$($fi_s:tt)*]
        @field[$name:ident : $t:ty]
        @tags[WithNotifier $(, $rest_tag:ident)*]
    ) => {
        $crate::_field_split_tags!(
            @ctx[$($ctx)*]
            @fi_n[$($fin_name : $fin_type ,)* $name : $t ,]
            @fi_g[$($fi_g)*]
            @fi_s[$($fi_s)*]
            @field[$name : $t]
            @tags[$($rest_tag),*]
        );
    };

    // WithGetter: add field to fi_g list, recurse with remaining tags
    (
        @ctx[$($ctx:tt)*]
        @fi_n[$($fi_n:tt)*]
        @fi_g[$($fig_name:ident : $fig_type:ty ,)*]
        @fi_s[$($fi_s:tt)*]
        @field[$name:ident : $t:ty]
        @tags[WithGetter $(, $rest_tag:ident)*]
    ) => {
        $crate::_field_split_tags!(
            @ctx[$($ctx)*]
            @fi_n[$($fi_n)*]
            @fi_g[$($fig_name : $fig_type ,)* $name : $t ,]
            @fi_s[$($fi_s)*]
            @field[$name : $t]
            @tags[$($rest_tag),*]
        );
    };

    // WithSetter: add field to fi_s list, recurse with remaining tags
    (
        @ctx[$($ctx:tt)*]
        @fi_n[$($fi_n:tt)*]
        @fi_g[$($fi_g:tt)*]
        @fi_s[$($fis_name:ident : $fis_type:ty ,)*]
        @field[$name:ident : $t:ty]
        @tags[WithSetter $(, $rest_tag:ident)*]
    ) => {
        $crate::_field_split_tags!(
            @ctx[$($ctx)*]
            @fi_n[$($fi_n)*]
            @fi_g[$($fi_g)*]
            @fi_s[$($fis_name : $fis_type ,)* $name : $t ,]
            @field[$name : $t]
            @tags[$($rest_tag),*]
        );
    };

    // Unrecognized tag
    (
        @ctx[$($ctx:tt)*]
        @fi_n[$($fi_n:tt)*]
        @fi_g[$($fi_g:tt)*]
        @fi_s[$($fi_s:tt)*]
        @field[$name:ident : $_t:ty]
        @tags[$unknown:ident $(, $rest_tag:ident)*]
    ) => {
        compile_error!(concat!(
            "interface!: unrecognized field tag `",
            stringify!($unknown),
            "` on field `",
            stringify!($name),
            "`. Supported tags: WithGetter, WithSetter, WithNotifier."
        ));
    };
}

/// Internal recursive-macro helper for `interface!`.
///
/// Accumulates members into typed lists, then calls the mixed generator macros.
/// Field members MUST carry at least one capability tag: `Field<T, WithGetter + WithSetter + WithNotifier>`.
/// `Field<T>` without tags is a compile error.
/// Tags control which consumer-side infrastructure is generated per field:
///  - `WithGetter`   - `{name}_get: R::FieldGetCaller<T>` + `get_{name}()` async wrapper
///  - `WithSetter`   - `{name}_set: R::FieldSetCaller<T>` + `set_{name}(val)` async wrapper
///  - `WithNotifier` - `{name}: R::FieldSubscriber<T>` (subscribe / notifications)
/// Any combination and any ordering of tags is supported.
///
/// Fields are split into three flat lists during accumulation:
///  @fi_n  - fields with WithNotifier tag (name:type)
///  @fi_g  - fields with WithGetter tag (name:type)
///  @fi_s  - fields with WithSetter tag (name:type)
/// A field with multiple tags appears in multiple lists.
/// The plain @fi list (name:type only) is still kept for forwarding to interface_producer_mixed!.
#[doc(hidden)]
#[macro_export]
macro_rules! _interface_collect_members {
    // Base case: nothing left - emit the mixed consumer and producer.
    (
        @id[$id:ident, $uid:expr]
        @ev[$($ev_name:ident : $ev_type:ty ,)*]
        @fi[$($fi_name:ident : $fi_type:ty ,)*]
        @fi_n[$($fin_name:ident : $fin_type:ty ,)*]
        @fi_g[$($fig_name:ident : $fig_type:ty ,)*]
        @fi_s[$($fis_name:ident : $fis_type:ty ,)*]
        @me[$($me_name:ident [$($me_arg_ty:ty),*] -> $me_ret:ty ,)*]
        $(,)?
    ) => {
        $crate::interface_consumer_mixed!(
            $id,
            events[$($ev_name : $ev_type ,)*],
            fields_notifier[$($fin_name : $fin_type ,)*],
            fields_getter[$($fig_name : $fig_type ,)*],
            fields_setter[$($fis_name : $fis_type ,)*],
            methods[$($me_name [$($me_arg_ty),*] -> $me_ret ,)*]
        );
        $crate::interface_producer_mixed!(
            $id,
            events[$($ev_name : $ev_type ,)*],
            fields[$($fi_name : $fi_type ,)*],
            methods[$($me_name [$($me_arg_ty),*] -> $me_ret ,)*]
        );
    };

    // Event member: `name : Event<T> ,?`
    (
        @id[$id:ident, $uid:expr]
        @ev[$($ev_name:ident : $ev_type:ty ,)*]
        @fi[$($fi_name:ident : $fi_type:ty ,)*]
        @fi_n[$($fin_name:ident : $fin_type:ty ,)*]
        @fi_g[$($fig_name:ident : $fig_type:ty ,)*]
        @fi_s[$($fis_name:ident : $fis_type:ty ,)*]
        @me[$($me_name:ident [$($me_arg_ty:ty),*] -> $me_ret:ty ,)*]
        $name:ident : Event<$t:ty>
        $(, $($rest:tt)*)?
    ) => {
        $crate::_interface_collect_members!(
            @id[$id, $uid]
            @ev[$($ev_name : $ev_type ,)* $name : $t ,]
            @fi[$($fi_name : $fi_type ,)*]
            @fi_n[$($fin_name : $fin_type ,)*]
            @fi_g[$($fig_name : $fig_type ,)*]
            @fi_s[$($fis_name : $fis_type ,)*]
            @me[$($me_name [$($me_arg_ty),*] -> $me_ret ,)*]
            $($($rest)*)?
        );
    };

    // Field member WITH tags: `name : Field<T, Tag1 + Tag2 + ...> ,?`
    // Delegates to _field_split_tags! to distribute the field into the per-tag flat lists.
    (
        @id[$id:ident, $uid:expr]
        @ev[$($ev_name:ident : $ev_type:ty ,)*]
        @fi[$($fi_name:ident : $fi_type:ty ,)*]
        @fi_n[$($fin_name:ident : $fin_type:ty ,)*]
        @fi_g[$($fig_name:ident : $fig_type:ty ,)*]
        @fi_s[$($fis_name:ident : $fis_type:ty ,)*]
        @me[$($me_name:ident [$($me_arg_ty:ty),*] -> $me_ret:ty ,)*]
        $name:ident : Field<$t:ty, $first_tag:ident $(+ $rest_tag:ident)*>
        $(, $($rest:tt)*)?
    ) => {
        $crate::_field_split_tags!(
            @ctx[
                @id[$id, $uid]
                @ev[$($ev_name : $ev_type ,)*]
                @fi[$($fi_name : $fi_type ,)* $name : $t ,]
                @me[$($me_name [$($me_arg_ty),*] -> $me_ret ,)*]
                @rest[$($($rest)*)?]
            ]
            @fi_n[$($fin_name : $fin_type ,)*]
            @fi_g[$($fig_name : $fig_type ,)*]
            @fi_s[$($fis_name : $fis_type ,)*]
            @field[$name : $t]
            @tags[$first_tag $(, $rest_tag)*]
        );
    };

    // Field member WITHOUT tags: `name : Field<T> ,?` — compile error.
    (
        @id[$_id:ident, $_uid:expr]
        @ev[$($ev_name:ident : $ev_type:ty ,)*]
        @fi[$($fi_name:ident : $fi_type:ty ,)*]
        @fi_n[$($fin_name:ident : $fin_type:ty ,)*]
        @fi_g[$($fig_name:ident : $fig_type:ty ,)*]
        @fi_s[$($fis_name:ident : $fis_type:ty ,)*]
        @me[$($me_name:ident [$($me_arg_ty:ty),*] -> $me_ret:ty ,)*]
        $name:ident : Field<$_t:ty>
        $(, $($rest:tt)*)?
    ) => {
        compile_error!(concat!(
            "interface!: Field member `",
            stringify!($name),
            "` requires at least one capability tag.\n",
            "Supported tags: WithGetter, WithSetter, WithNotifier\n",
            "Use the `+` syntax to combine tags, e.g.:\n",
            "  ", stringify!($name), ": Field<T, WithGetter + WithSetter + WithNotifier>\n",
            "  ", stringify!($name), ": Field<T, WithGetter>\n",
            "  ", stringify!($name), ": Field<T, WithSetter>\n",
            "  ", stringify!($name), ": Field<T, WithNotifier>\n",
            "Tags control which consumer-side infrastructure is generated:\n",
            "  WithGetter   - get_*()\n",
            "  WithSetter   - set_*()\n",
            "  WithNotifier - subscribe()\n",
        ));
    };

    // Method member (fn-like syntax): `name(Arg0, Arg1, ...) -> Ret ,?`
    (
        @id[$id:ident, $uid:expr]
        @ev[$($ev_name:ident : $ev_type:ty ,)*]
        @fi[$($fi_name:ident : $fi_type:ty ,)*]
        @fi_n[$($fin_name:ident : $fin_type:ty ,)*]
        @fi_g[$($fig_name:ident : $fig_type:ty ,)*]
        @fi_s[$($fis_name:ident : $fis_type:ty ,)*]
        @me[$($me_name:ident [$($me_arg_ty:ty),*] -> $me_ret:ty ,)*]
        $name:ident ( $($arg_ty:ty),* ) -> $ret:ty
        $(, $($rest:tt)*)?
    ) => {
        $crate::_interface_collect_members!(
            @id[$id, $uid]
            @ev[$($ev_name : $ev_type ,)*]
            @fi[$($fi_name : $fi_type ,)*]
            @fi_n[$($fin_name : $fin_type ,)*]
            @fi_g[$($fig_name : $fig_type ,)*]
            @fi_s[$($fis_name : $fis_type ,)*]
            @me[$($me_name [$($me_arg_ty),*] -> $me_ret ,)* $name [$($arg_ty),*] -> $ret ,]
            $($($rest)*)?
        );
    };

    // Catch-all: unrecognized member - emit a clear compile-time error.
    (
        @id[$_id:ident, $_uid:expr]
        @ev[$($ev_name:ident : $ev_type:ty ,)*]
        @fi[$($fi_name:ident : $fi_type:ty ,)*]
        @fi_n[$($fin_name:ident : $fin_type:ty ,)*]
        @fi_g[$($fig_name:ident : $fig_type:ty ,)*]
        @fi_s[$($fis_name:ident : $fis_type:ty ,)*]
        @me[$($me_name:ident [$($me_arg_ty:ty),*] -> $me_ret:ty ,)*]
        $($unknown:tt)+
    ) => {
        compile_error!(concat!(
            "interface!: unrecognized member syntax: `",
            stringify!($($unknown)+),
            "`.\n",
            "Supported member types:\n",
            "  name: Event<T>                                           - event subscriber / publisher pair\n",
            "  name: Field<T, WithGetter + WithSetter + WithNotifier>   - field with capability tags\n",
            "  name(Arg0, Arg1, ...) -> Ret                             - method caller / handler pair\n",
            "Note: Field<T> without tags is not allowed. Specify at least one of:\n",
            "  WithGetter, WithSetter, WithNotifier\n",
            "Example:\n",
            "  interface!(interface MyIface {\n",
            "      my_event: Event<MyData>,\n",
            "      my_field: Field<MyData, WithGetter + WithSetter + WithNotifier>,\n",
            "      my_method(MyData) -> MyData,\n",
            "  });"
        ));
    };
}

/// Macro to create a unique interface struct and implement the Interface trait for it.
///
/// Generates the INTERFACE_ID constant and associated Consumer/Producer types.
/// INTERFACE_ID is generated by default as the module path + interface name,
/// but can be overridden by providing a custom UID as a second parameter to the macro.
#[macro_export]
macro_rules! interface_common {
    // Default: auto ID = module path + type name
    ($id:ident) => {
        score_com::paste::paste! {
            pub struct [<$id Interface>] {}
            impl score_com::Interface for [<$id Interface>] {
                const INTERFACE_ID: &'static str =
                    concat!(module_path!(), "::", stringify!($id));
                type Consumer<R: score_com::Runtime + ?Sized> = [<$id Consumer>]<R>;
                type Producer<R: score_com::Runtime + ?Sized> = [<$id Producer>]<R>;
            }
        }
    };
    // Explicit ID override
    ($id:ident, $uid:expr) => {
        score_com::paste::paste! {
            pub struct [<$id Interface>] {}
            impl score_com::Interface for [<$id Interface>] {
                const INTERFACE_ID: &'static str = $uid;
                type Consumer<R: score_com::Runtime + ?Sized> = [<$id Consumer>]<R>;
                type Producer<R: score_com::Runtime + ?Sized> = [<$id Producer>]<R>;
            }
        }
    };
}

/// Macro to implement the Consumer trait for a given interface ID and its events.
///
/// Generates the Consumer struct with subscribers for each event.
// TODO: This can be removed once verification is done that the new interface_producer_mixed! macro works for event-only interfaces.
#[macro_export]
macro_rules! interface_consumer {
    ($id:ident, $($event_name:ident, Event<$event_type:ty>),+$(,)?) => {
        score_com::paste::paste!  {
            pub struct [<$id Consumer>]<R: score_com::Runtime + ?Sized> {
                $(
                    pub $event_name: R::Subscriber<$event_type>,
                )+
            }

            impl<R: score_com::Runtime + ?Sized> score_com::Consumer<R> for [<$id Consumer>]<R> {
                fn new(instance_info: R::ConsumerInfo) -> Self {
                    [<$id Consumer>] {
                        $(
                            $event_name: R::Subscriber::new(
                                stringify!($event_name),
                                instance_info.clone()
                            ).expect(&format!(
                                "Failed to create subscriber for {}",
                                stringify!($event_name)
                            )),
                        )+
                    }
                }
            }
        }
    };
}

/// This is Event specific.
/// Macro to implement the Producer and OfferedProducer traits for
/// a given interface ID and its events.
/// Generates Producer and OfferedProducer structs with publishers for each event.
// TODO: This can be removed once verification is done that the new interface_producer_mixed! macro works for event-only interfaces.
#[macro_export]
macro_rules! interface_producer {
    ($id:ident, $($event_name:ident, Event<$event_type:ty>),+$(,)?) => {
        score_com::paste::paste!  {
            pub struct [<$id Producer>]<R: score_com::Runtime + ?Sized> {
                _runtime: core::marker::PhantomData<R>,
                instance_info: R::ProviderInfo,
            }

            pub struct [<$id OfferedProducer>]<R: score_com::Runtime + ?Sized> {
                $(
                    pub $event_name: R::Publisher<$event_type>,
                )+
                instance_info: R::ProviderInfo,
            }

            impl<R: score_com::Runtime + ?Sized> score_com::Producer<R> for [<$id Producer>]<R> {
                type Interface = [<$id Interface>];
                type OfferedProducer = [<$id OfferedProducer>]<R>;
                fn offer(self) -> score_com::Result<Self::OfferedProducer> {
                    let offered = [<$id OfferedProducer>] {
                        $(
                            $event_name: R::Publisher::new(
                                stringify!($event_name),
                                self.instance_info.clone()
                            ).expect(&format!(
                                "Failed to create publisher for {}",
                                stringify!($event_name)
                            )),
                        )+
                        instance_info: self.instance_info.clone(),
                    };
                    // Offer the service instance to make it discoverable
                    self.instance_info.offer_service()?;
                    Ok(offered)
                }

                fn new(instance_info: R::ProviderInfo) -> score_com::Result<Self> {
                    Ok([<$id Producer>] {
                        _runtime: core::marker::PhantomData,
                        instance_info,
                    })
                }
            }

            impl<R: score_com::Runtime + ?Sized> score_com::OfferedProducer<R>
                for [<$id OfferedProducer>]<R> {
                type Interface = [<$id Interface>];
                type Producer = [<$id Producer>]<R>;
                fn unoffer(self) -> score_com::Result<Self::Producer> {
                    let producer = [<$id Producer>] {
                        _runtime: core::marker::PhantomData,
                        instance_info: self.instance_info.clone(),
                    };
                    // Stop offering the service instance to withdraw it from system availability
                    self.instance_info.stop_offer_service()?;
                    Ok(producer)
                }
            }
        }
    };
}

/// Per-tag struct field declaration helper for `interface_consumer_mixed!`.
///
/// Called once per field member; iterates over the tag list and emits one struct field per tag.
/// - `WithNotifier` - `pub $name: R::FieldSubscriber<$type>,`
/// - `WithGetter`   - `pub {name}_get: R::FieldGetCaller<$type>,`
/// - `WithSetter`   - `pub {name}_set: R::FieldSetCaller<$type>,`
/// Any ordering of tags is supported; unrecognized tags produce a compile error.
///
/// NOTE: Must be called inside a `score_com::paste::paste! { pub struct ... { HERE } }` block
/// since it uses `[<>]` identifier concatenation.
#[doc(hidden)]
#[macro_export]
macro_rules! _field_consumer_decl {
    // Base: no more tags
    ($fi_name:ident, $fi_type:ty, []) => {};

    // WithNotifier: emit FieldSubscriber field, recurse
    ($fi_name:ident, $fi_type:ty, [WithNotifier $(, $rest:ident)*]) => {
        pub $fi_name: R::FieldSubscriber<$fi_type>,
        $crate::_field_consumer_decl!($fi_name, $fi_type, [$($rest),*]);
    };

    // WithGetter: emit FieldGetCaller field
    ($fi_name:ident, $fi_type:ty, [WithGetter $(, $rest:ident)*]) => {
        pub [<$fi_name _get>]: R::FieldGetCaller<$fi_type>,
        $crate::_field_consumer_decl!($fi_name, $fi_type, [$($rest),*]);
    };

    // WithSetter: emit FieldSetCaller field
    ($fi_name:ident, $fi_type:ty, [WithSetter $(, $rest:ident)*]) => {
        pub [<$fi_name _set>]: R::FieldSetCaller<$fi_type>,
        $crate::_field_consumer_decl!($fi_name, $fi_type, [$($rest),*]);
    };

    // Unrecognized tag
    ($fi_name:ident, $fi_type:ty, [$unknown:ident $(, $rest:ident)*]) => {
        compile_error!(concat!(
            "interface!: unrecognized field tag `",
            stringify!($unknown),
            "`. Supported tags: WithGetter, WithSetter, WithNotifier."
        ));
    };
}

/// Per-tag struct field initializer helper for `interface_consumer_mixed!`.
///
/// Emits one initializer expression per tag (used inside the `Consumer::new()` struct literal).
/// - `WithNotifier` - `$name: R::FieldSubscriber::new(...)`
/// - `WithGetter`   - `{name}_get: <R::FieldGetCaller<T> as MethodCaller<(), T, R>>::new(...)`
/// - `WithSetter`   - `{name}_set: <R::FieldSetCaller<T> as MethodCaller<(T,), T, R>>::new(...)`
///
/// NOTE: Must be called inside a `score_com::paste::paste! { Struct { HERE } }` block.
#[doc(hidden)]
#[macro_export]
macro_rules! _field_consumer_init {
    // Base: no more tags
    ($fi_name:ident, $fi_type:ty, [], $instance_info:ident) => {};

    // WithNotifier: emit FieldSubscriber init, recurse
    ($fi_name:ident, $fi_type:ty, [WithNotifier $(, $rest:ident)*], $instance_info:ident) => {
        $fi_name: R::FieldSubscriber::new(
            stringify!($fi_name),
            $instance_info.clone()
        ).expect(&format!(
            "Failed to create field subscriber for {}",
            stringify!($fi_name)
        )),
        $crate::_field_consumer_init!($fi_name, $fi_type, [$($rest),*], $instance_info);
    };

    // WithGetter: emit FieldGetCaller init
    ($fi_name:ident, $fi_type:ty, [WithGetter $(, $rest:ident)*], $instance_info:ident) => {
        [<$fi_name _get>]: <R::FieldGetCaller<$fi_type>
            as score_com::MethodCaller<(), $fi_type, R>>::new(
                concat!(stringify!($fi_name), "_get"),
                $instance_info.clone()
            ).expect(&format!(
                "Failed to create field get caller for {}",
                stringify!($fi_name)
            )),
        $crate::_field_consumer_init!($fi_name, $fi_type, [$($rest),*], $instance_info);
    };

    // WithSetter: emit FieldSetCaller init
    ($fi_name:ident, $fi_type:ty, [WithSetter $(, $rest:ident)*], $instance_info:ident) => {
        [<$fi_name _set>]: <R::FieldSetCaller<$fi_type>
            as score_com::MethodCaller<($fi_type,), $fi_type, R>>::new(
                concat!(stringify!($fi_name), "_set"),
                $instance_info.clone()
            ).expect(&format!(
                "Failed to create field set caller for {}",
                stringify!($fi_name)
            )),
        $crate::_field_consumer_init!($fi_name, $fi_type, [$($rest),*], $instance_info);
    };

    // Unrecognized tag (already caught by _field_consumer_decl, but guard here too)
    ($fi_name:ident, $fi_type:ty, [$unknown:ident $(, $rest:ident)*], $instance_info:ident) => {
        compile_error!(concat!(
            "interface!: unrecognized field tag `",
            stringify!($unknown),
            "`. Supported tags: WithGetter, WithSetter, WithNotifier."
        ));
    };
}

/// Per-tag wrapper method helper for `interface_consumer_mixed!`.
///
/// Emits one wrapper method per tag inside the `impl {Id}Consumer<R>` block.
/// - `WithNotifier` - no method generated (subscribe is called directly on the struct field)
/// - `WithGetter`   - `pub fn get_{name}<'a>(&'a self) -> impl Future<Output = Result<...>> + 'a`
/// - `WithSetter`   - `pub fn set_{name}<'a>(&'a self, value: T) -> impl Future<Output = Result<...>> + 'a`
///
/// NOTE: Must be called inside a `score_com::paste::paste! { impl ... { HERE } }` block.
#[doc(hidden)]
#[macro_export]
macro_rules! _field_consumer_methods {
    // Base: no more tags
    ($fi_name:ident, $fi_type:ty, []) => {};

    // WithNotifier: no method generated - subscribe is on the struct field directly
    ($fi_name:ident, $fi_type:ty, [WithNotifier $(, $rest:ident)*]) => {
        $crate::_field_consumer_methods!($fi_name, $fi_type, [$($rest),*]);
    };

    // WithGetter: emit get_{name}() async wrapper (uses [<>] - must be inside paste!)
    ($fi_name:ident, $fi_type:ty, [WithGetter $(, $rest:ident)*]) => {
        /// Asynchronously get the current value of the field.
        /// Returns a future that resolves to `Result<R::MethodReturnSample<T>>`.
        /// Independent of subscription lifecycle - available before and after `subscribe()`.
        pub fn [<get_ $fi_name>]<'a>(
            &'a self,
        ) -> impl core::future::Future<Output = score_com::Result<<R as score_com::Runtime>::MethodReturnSample<$fi_type>>> + 'a {
            score_com::MethodCaller::invoke_with_copy(&self.[<$fi_name _get>], ())
        }
        $crate::_field_consumer_methods!($fi_name, $fi_type, [$($rest),*]);
    };

    // WithSetter: emit set_{name}(value) async wrapper (uses [<>] - must be inside paste!)
    ($fi_name:ident, $fi_type:ty, [WithSetter $(, $rest:ident)*]) => {
        /// Asynchronously set the value of the field.
        /// Returns a future that resolves to `Result<R::MethodReturnSample<T>>`
        /// containing the confirmed field value from the producer.
        /// Independent of subscription lifecycle - available before and after `subscribe()`.
        pub fn [<set_ $fi_name>]<'a>(
            &'a self,
            value: $fi_type,
        ) -> impl core::future::Future<Output = score_com::Result<<R as score_com::Runtime>::MethodReturnSample<$fi_type>>> + 'a {
            score_com::MethodCaller::invoke_with_copy(&self.[<$fi_name _set>], (value,))
        }
        $crate::_field_consumer_methods!($fi_name, $fi_type, [$($rest),*]);
    };

    // Unrecognized tag
    ($fi_name:ident, $fi_type:ty, [$unknown:ident $(, $rest:ident)*]) => {
        compile_error!(concat!(
            "interface!: unrecognized field tag `",
            stringify!($unknown),
            "`. Supported tags: WithGetter, WithSetter, WithNotifier."
        ));
    };
}

/// Generates the `{id}Consumer<R>` struct and its `Consumer<R>` trait implementation for
/// interfaces that may contain any combination of events, fields, and methods.
///
/// Field members are passed as three separate flat lists (one per tag type):
/// - `fields_notifier[name:type,...]` - `pub name: R::FieldSubscriber<T>` (subscribe/notifications)
/// - `fields_getter[name:type,...]`   - `pub name_get: R::FieldGetCaller<T>` + `get_name()` wrapper
/// - `fields_setter[name:type,...]`   - `pub name_set: R::FieldSetCaller<T>` + `set_name(val)` wrapper
///
/// A field with multiple tags (e.g. `WithGetter + WithSetter`) appears in multiple lists.
/// Method members get positional-arg wrapper functions via `_gen_method_wrapper!`.
#[doc(hidden)]
#[macro_export]
macro_rules! interface_consumer_mixed {
    (
        $id:ident,
        events[$($ev_name:ident : $ev_type:ty ,)*],
        fields_notifier[$($fin_name:ident : $fin_type:ty ,)*],
        fields_getter[$($fig_name:ident : $fig_type:ty ,)*],
        fields_setter[$($fis_name:ident : $fis_type:ty ,)*],
        methods[$($me_name:ident [$($me_arg_ty:ty),*] -> $me_ret:ty ,)*]
    ) => {
        score_com::paste::paste! {
            pub struct [<$id Consumer>]<R: score_com::Runtime + ?Sized> {
                $(
                    pub $ev_name: R::Subscriber<$ev_type>,
                )*
                $(
                    pub $fin_name: R::FieldSubscriber<$fin_type>,
                )*
                $(
                    pub [<$fig_name _get>]: R::FieldGetCaller<$fig_type>,
                )*
                $(
                    pub [<$fis_name _set>]: R::FieldSetCaller<$fis_type>,
                )*
                $(
                    pub $me_name: R::MethodCaller<($($me_arg_ty,)*), $me_ret>,
                )*
            }

            impl<R: score_com::Runtime + ?Sized> score_com::Consumer<R> for [<$id Consumer>]<R> {
                fn new(instance_info: R::ConsumerInfo) -> Self {
                    [<$id Consumer>] {
                        $(
                            $ev_name: R::Subscriber::new(
                                stringify!($ev_name),
                                instance_info.clone()
                            ).expect(&format!(
                                "Failed to create subscriber for {}",
                                stringify!($ev_name)
                            )),
                        )*
                        $(
                            $fin_name: R::FieldSubscriber::new(
                                stringify!($fin_name),
                                instance_info.clone()
                            ).expect(&format!(
                                "Failed to create field subscriber for {}",
                                stringify!($fin_name)
                            )),
                        )*
                        $(
                            [<$fig_name _get>]: <R::FieldGetCaller<$fig_type>
                                as score_com::MethodCaller<(), $fig_type, R>>::new(
                                    concat!(stringify!($fig_name), "_get"),
                                    instance_info.clone()
                                ).expect(&format!(
                                    "Failed to create field get caller for {}",
                                    stringify!($fig_name)
                                )),
                        )*
                        $(
                            [<$fis_name _set>]: <R::FieldSetCaller<$fis_type>
                                as score_com::MethodCaller<($fis_type,), $fis_type, R>>::new(
                                    concat!(stringify!($fis_name), "_set"),
                                    instance_info.clone()
                                ).expect(&format!(
                                    "Failed to create field set caller for {}",
                                    stringify!($fis_name)
                                )),
                        )*
                        $(
                            $me_name: <R::MethodCaller<($($me_arg_ty,)*), $me_ret>
                                as score_com::MethodCaller<($($me_arg_ty,)*), $me_ret, R>>::new(
                                    stringify!($me_name),
                                    instance_info.clone()
                                ).expect(&format!(
                                    "Failed to create method caller for {}",
                                    stringify!($me_name)
                                )),
                        )*
                    }
                }
            }

            // Method wrappers: positional-arg convenience functions via MethodCallInput.
            // Field get/set wrappers: async get/set via FieldGetCaller/FieldSetCaller.
            // subscribe() is available directly on the struct field for WithNotifier fields.
            impl<R: score_com::Runtime + ?Sized> [<$id Consumer>]<R> {
                $(
                    $crate::_gen_method_wrapper!($me_name ($($me_arg_ty),*) -> $me_ret);
                )*
                $(
                    /// Asynchronously get the current value of the field.
                    /// Returns a future that resolves to `Result<R::MethodReturnSample<T>>`.
                    /// Independent of subscription lifecycle.
                    pub fn [<get_ $fig_name>]<'a>(
                        &'a self,
                    ) -> impl core::future::Future<Output = score_com::Result<<R as score_com::Runtime>::MethodReturnSample<$fig_type>>> + 'a {
                        score_com::MethodCaller::invoke_with_copy(&self.[<$fig_name _get>], ())
                    }
                )*
                $(
                    /// Asynchronously set the value of the field.
                    /// Returns a future that resolves to `Result<R::MethodReturnSample<T>>`
                    /// containing the confirmed field value from the producer.
                    /// Independent of subscription lifecycle.
                    pub fn [<set_ $fis_name>]<'a>(
                        &'a self,
                        value: $fis_type,
                    ) -> impl core::future::Future<Output = score_com::Result<<R as score_com::Runtime>::MethodReturnSample<$fis_type>>> + 'a {
                        score_com::MethodCaller::invoke_with_copy(&self.[<$fis_name _set>], (value,))
                    }
                )*
            }
        }
    };
}

/// Generates `{id}Producer<R>`, `{id}OfferedProducer<R>`, and all trait implementations for
/// interfaces that may contain any combination of events, fields, and methods.
///
/// # Design
/// - Event publishers (`R::Publisher<T>`) are created *lazily during `_offer_internal()`*
///   so they are only present on the `OfferedProducer`.
/// - Field publishers (`R::FieldPublisher<T>`) are created eagerly in `Producer::new()` and
///   moved into `OfferedProducer` when the service is offered.
/// - Method handlers (`R::MethodHandler<Args, Ret>`) likewise created eagerly and moved.
///
/// When the interface has at least one field or method member, the `Producer` struct derives
/// `TypeStateValidator` which generates the `.init()` entry point and the `update_*` /
/// `register_set_handler_*` / `register_*_handler` chain required before `offer()`.
///
/// When the interface has only events (no fields, no methods), a plain `offer()` is generated
/// directly (matching the existing event-only pattern).
#[doc(hidden)]
#[macro_export]
macro_rules! interface_producer_mixed {
    // Event-only specialisation (no fields, no methods):
    // plain offer() without type-state validation - identical to interface_producer!
    (
        $id:ident,
        events[$($ev_name:ident : $ev_type:ty ,)+],
        fields[],
        methods[]
    ) => {
        $crate::interface_producer!($id, $($ev_name, Event<$ev_type>),+);
    };

    // General case: at least one field or method (or both), possibly with events too.
    (
        $id:ident,
        events[$($ev_name:ident : $ev_type:ty ,)*],
        fields[$($fi_name:ident : $fi_type:ty ,)*],
        methods[$($me_name:ident [$($me_arg_ty:ty),*] -> $me_ret:ty ,)*]
    ) => {
        score_com::paste::paste! {
            // Producer struct - derives TypeStateValidator for compile-time offer() gating.
            // Fields: FieldPublisher per field + MethodHandler per method.
            // Event publishers are NOT stored here; they are created during _offer_internal().
            #[derive($crate::score_com_macros::TypeStateValidator)]
            pub struct [<$id Producer>]<R: score_com::Runtime + ?Sized> {
                $(
                    $fi_name: R::FieldPublisher<$fi_type>,
                )*
                $(
                    $me_name: R::MethodHandler<($($me_arg_ty,)*), $me_ret>,
                )*
                pub instance_info: R::ProviderInfo,
            }

            // OfferedProducer struct - contains event publishers (created on offer),
            // plus the moved field publishers and method handlers from Producer.
            pub struct [<$id OfferedProducer>]<R: score_com::Runtime + ?Sized> {
                $(
                    pub $ev_name: R::Publisher<$ev_type>,
                )*
                $(
                    pub $fi_name: R::FieldPublisher<$fi_type>,
                )*
                $(
                    $me_name: R::MethodHandler<($($me_arg_ty,)*), $me_ret>,
                )*
                instance_info: R::ProviderInfo,
            }

            // Internal implementation - called by the TypeStateValidator's offer() after all
            // states have been validated at compile time.
            impl<R: score_com::Runtime + ?Sized> [<$id Producer>]<R> {
                #[doc(hidden)]
                pub fn _offer_internal(
                    self,
                ) -> score_com::Result<[<$id OfferedProducer>]<R>> {
                    let offered = [<$id OfferedProducer>] {
                        $(
                            $ev_name: R::Publisher::new(
                                stringify!($ev_name),
                                self.instance_info.clone()
                            ).expect(&format!(
                                "Failed to create publisher for {}",
                                stringify!($ev_name)
                            )),
                        )*
                        $(
                            $fi_name: self.$fi_name,
                        )*
                        $(
                            $me_name: self.$me_name,
                        )*
                        instance_info: self.instance_info.clone(),
                    };
                    self.instance_info.offer_service()?;
                    Ok(offered)
                }
            }

            // We can not remove the offer method from the Producer trait, but we can override it to panic with a clear message.
            // Also adding compiler warning or error for this is not possible, we will rely on documentation and panic.
            // if user call this directly, then it will panic and it is against the intended usage of the APIs.
            // TODO: Need to think about this more, when we have more complex interface with mixed types.
            // Also update the documentation for this, so user should not call offer() directly from Producer struct.
            impl<R: score_com::Runtime + ?Sized> score_com::Producer<R> for [<$id Producer>]<R> {
                type Interface = [<$id Interface>];
                type OfferedProducer = [<$id OfferedProducer>]<R>;

                fn offer(self) -> score_com::Result<Self::OfferedProducer> {
                    panic!(
                        "ERROR: Cannot call {producer}.offer() directly.\n\
                         All fields must be initialized and all handlers must be registered first.\n\
                         Correct usage: producer.init()\
                             .update_<field>(&val)?\
                             .register_set_handler_<field>(|v| {{ ... }})\
                             .register_<method>_handler(|args| {{ ... }})\
                             .offer()?",
                        producer = stringify!([<$id Producer>])
                    )
                }

                fn new(instance_info: R::ProviderInfo) -> score_com::Result<Self> {
                    Ok([<$id Producer>] {
                        $(
                            $fi_name: R::FieldPublisher::new(
                                stringify!($fi_name),
                                instance_info.clone()
                            )?,
                        )*
                        $(
                            $me_name: <R::MethodHandler<($($me_arg_ty,)*), $me_ret>
                                as score_com::MethodHandler<($($me_arg_ty,)*), $me_ret, R>>::new(
                                    stringify!($me_name),
                                    instance_info.clone()
                                )?,
                        )*
                        instance_info,
                    })
                }
            }

            // OfferedProducer trait impl - unoffer() stops the service and returns the Producer.
            impl<R: score_com::Runtime + ?Sized> score_com::OfferedProducer<R>
                for [<$id OfferedProducer>]<R>
            {
                type Interface = [<$id Interface>];
                type Producer = [<$id Producer>]<R>;

                fn unoffer(self) -> score_com::Result<Self::Producer> {
                    self.instance_info.stop_offer_service()?;
                    Ok([<$id Producer>] {
                        $(
                            $fi_name: self.$fi_name,
                        )*
                        $(
                            $me_name: self.$me_name,
                        )*
                        instance_info: self.instance_info,
                    })
                }
            }
        }
    };
}

/// Entry-point wrapper generator.
/// Every generated wrapper returns `impl Future<Output = score_com::Result<R::MethodReturnSample<Return>>> + '_`.
///
/// # Generated call sites
/// ```text
/// consumer.method(val).await  - copy path   - val: ArgType
/// consumer.method(ptr).await  - zero-copy   - ptr: MethodInArgPtr<ArgType>
/// ```
#[doc(hidden)]
#[macro_export]
macro_rules! _gen_method_wrapper {
    // 0 args - invoke_with_copy directly; no zero-copy path (nothing to allocate).
    // This is for kind of `get` methods that take no arguments and return a value.
    ($me_name:ident () -> $me_ret:ty) => {
        pub fn $me_name<'a>(&'a self) -> impl core::future::Future<Output = score_com::Result<<R as score_com::Runtime>::MethodReturnSample<$me_ret>>> + 'a {
            score_com::MethodCaller::invoke_with_copy(&self.$me_name, ())
        }
    };
    // 1-N args - delegate to the self-counting recursive macro.
    ($me_name:ident ($($t:ty),+) -> $me_ret:ty) => {
        $crate::_gen_method_wrapper_collect!(
            $me_name -> $me_ret ;
            @counter[]
            @acc[]
            @types[$($t),+]
        );
    };
}

/// Recursive macro for `_gen_method_wrapper!`.
///
/// Self-counting: instead of zipping the method's positional type list against a
/// pre-defined pool of `(arg_name, generic_name)` identifiers, this recursive macro synthesizes
/// a fresh, unique `(argN : _AN : TypeN)` triplet at each recursion step directly from a
/// growing counter of `n` marker tokens (via `paste!`), then calls
/// `_gen_method_wrapper_body!` once the type list is exhausted.
///
/// This mirrors the self-contained recursion used by `impl_all_arities!` in
/// `method_arities.rs`: there is no separate pool to keep in sync, and no fixed
/// argument-count limit - any arity supported by `method_arities.rs` works automatically.
#[doc(hidden)]
#[macro_export]
macro_rules! _gen_method_wrapper_collect {
    // Base: all types consumed - emit the function via the body macro.
    (
        $me_name:ident -> $me_ret:ty ;
        @counter[$($n:tt)*]
        @acc[$($acc:tt),*]
        @types[]
    ) => {
        $crate::_gen_method_wrapper_body!($me_name -> $me_ret ; [$($acc),*]);
    };

    // Step: consume one type, grow the counter by one `n`, and synthesize a fresh
    // (param, generic) identifier pair from the counter via `paste!`.
    (
        $me_name:ident -> $me_ret:ty ;
        @counter[$($n:tt)*]
        @acc[$($acc:tt),*]
        @types[$t:ty $(, $rest_t:ty)*]
    ) => {
        score_com::paste::paste! {
            $crate::_gen_method_wrapper_collect!(
                $me_name -> $me_ret ;
                @counter[$($n)* n]
                @acc[$($acc,)* ([<arg $($n)*>] : [<_A $($n)*>] : $t)]
                @types[$($rest_t),*]
            );
        }
    };
}

/// Generates the wrapper function from an accumulated list of `(argN : _AN : TypeN)`.
///
/// This generates a wrapper function template.
/// All arities use this one arm - the function body is written once, not duplicated per arity.
/// Called by `_gen_method_wrapper_collect!` after it has built the full triplet list.
///
/// The generated function returns `impl Future<Output = score_com::Result<R::MethodReturnSample<$me_ret>>> + 'a` so callers
/// can `.await` the method call, e.g. `consumer.method_name(arg0).await?`.
#[doc(hidden)]
#[macro_export]
macro_rules! _gen_method_wrapper_body {
    ($me_name:ident -> $me_ret:ty ; [$(($p:ident : $g:ident : $c:ty)),+]) => {
        pub fn $me_name<'a, $($g),+>(
            &'a self,
            $($p: $g),+
        ) -> impl core::future::Future<Output = score_com::Result<<R as score_com::Runtime>::MethodReturnSample<$me_ret>>> + 'a
        where
            ($($g,)+): score_com::MethodCallInput<($($c,)+), $me_ret, R>,
            R::MethodCaller<($($c,)+), $me_ret>:
                score_com::MethodCaller<($($c,)+), $me_ret, R>,
        {
            score_com::MethodCallInput::invoke(($($p,)+), &self.$me_name)
        }
    };
}

mod tests {
    /// ```
    /// mod my_module {
    ///     use score_com::{interface,CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///
    ///     interface!(
    ///         interface Vehicle {
    ///             left_tire: Event<Tire>,
    ///             exhaust: Event<Exhaust>,
    ///         }
    ///     );
    /// }
    /// ```
    /// This will generate the following types and trait implementations:
    /// - `VehicleInterface` struct with `INTERFACE_ID = "my_module::Vehicle"`
    /// - `VehicleConsumer<R>`, `VehicleProducer<R>`, `VehicleOfferedProducer<R>` with appropriate
    ///   trait implementations for the Vehicle interface.
    #[cfg(doctest)]
    fn interface_macro_with_auto_id() {}

    /// ```
    /// mod my_module {
    ///     use score_com::{interface, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///
    ///     interface!(
    ///         interface Vehicle {
    ///            Id = "CustomVehicleInterface",
    ///             left_tire: Event<Tire>,
    ///             exhaust: Event<Exhaust>,
    ///         }
    ///     );
    /// }
    /// ```
    /// This will generate the following types and trait implementations:
    /// - `VehicleInterface` struct with `INTERFACE_ID = "CustomVehicleInterface"`
    /// - `VehicleConsumer<R>`, `VehicleProducer<R>`, `VehicleOfferedProducer<R>` with appropriate
    ///   trait implementations for the Vehicle interface.
    #[cfg(doctest)]
    fn interface_macro_with_custom_id() {}

    /// ```
    /// mod my_module {
    ///     use score_com::{interface, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///
    ///     interface!(
    ///         interface Vehicle, {
    ///            Id = "CustomVehicleInterface",
    ///             left_tire: Event<Tire>,
    ///             exhaust: Event<Exhaust>,
    ///         }
    ///     );
    /// }
    /// ```
    /// This will generate the following types and trait implementations:
    /// - `VehicleInterface` struct with `INTERFACE_ID = "CustomVehicleInterface"`
    /// - `VehicleConsumer<R>`, `VehicleProducer<R>`, `VehicleOfferedProducer<R>` with appropriate
    ///   trait implementations for the Vehicle interface.
    #[cfg(doctest)]
    fn interface_macro_with_custom_id_with_comma_for_backend_compatibility() {}

    /// Mixed interface (Event + Field + Method) with a custom ID.
    ///
    /// ```
    /// mod my_module {
    ///     use score_com::{interface, CommData, Reloc, ProviderInfo, Subscriber, Publisher,
    ///                     WithGetter, WithSetter, WithNotifier};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     interface!(
    ///         interface Vehicle {
    ///             Id = "AbcInterface",
    ///             left_tire: Event<Tire>,
    ///             left_tire_field: Field<Tire, WithGetter + WithSetter + WithNotifier>,
    ///             left_tire_method(Tire) -> Tire,
    ///         }
    ///     );
    /// }
    /// ```
    /// Generates `VehicleInterface`, `VehicleConsumer<R>`, `VehicleProducer<R>`,
    /// and `VehicleOfferedProducer<R>` where:
    /// - `VehicleConsumer<R>` has `left_tire: Subscriber<Tire>`,
    ///   `left_tire_field: FieldSubscriber<Tire>` (from `WithNotifier`),
    ///   `left_tire_field_get: FieldGetCaller<Tire>` (from `WithGetter`),
    ///   `left_tire_field_set: FieldSetCaller<Tire>` (from `WithSetter`),
    ///   `left_tire_method: MethodCaller<(Tire,), Tire>`,
    ///   and a convenience `left_tire_method(arg0: Tire)` method.
    /// - `VehicleProducer<R>` derives `TypeStateValidator` and requires the `.init()` chain:
    ///   `producer.init().update_left_tire_field(&val)?.register_set_handler_left_tire_field(f).register_left_tire_method_handler(h).offer()?`
    /// - `VehicleOfferedProducer<R>` has `left_tire: Publisher<Tire>` (created lazily on offer),
    ///   `left_tire_field: FieldPublisher<Tire>`, plus the active method handler.
    #[cfg(doctest)]
    fn interface_macro_mixed() {}

    /// ```compile_fail
    /// mod my_module {
    ///     use score_com::{interface, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///
    ///     interface!(
    ///         interface Vehicle {
    ///            Id = "CustomVehicleInterface",
    ///             left_tire: Method<Tire>,
    ///             exhaust: Method<Exhaust>,
    ///         }
    ///     );
    /// }
    /// ```
    /// This will fail to compile because `Method<T>` (old syntax without a return type) is not
    /// supported. Use fn-like syntax: `method_name(Args) -> Ret`.
    #[cfg(doctest)]
    fn interface_macro_with_old_method_syntax() {}

    /// ```compile_fail
    /// mod my_module {
    ///     use score_com::{interface, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     interface_common!(Vehicle, "CustomVehicleInterface", {
    ///         left_tire: Event<Tire>,
    ///     });
    /// }
    /// ```
    /// This will fail to compile because `interface_common!` does not accept member definitions.
    /// Use `interface!` for a complete interface definition.
    #[cfg(doctest)]
    fn interface_macro_with_Field() {}

    /// ```
    /// mod my_module {
    ///     use score_com::{interface_common, interface_consumer, interface_producer};
    ///     use score_com::{CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///     interface_common!(Vehicle);
    ///     interface_consumer!(Vehicle, left_tire, Event<Tire>, exhaust, Event<Exhaust>);
    ///     interface_producer!(Vehicle, left_tire, Event<Tire>, exhaust, Event<Exhaust>);
    /// }
    /// ```
    /// This will generate a `VehicleInterface` struct with an `INTERFACE_ID` constant that is
    /// automatically generated as the module path plus
    /// the interface name (e.g."my_module::Vehicle").
    /// It will also define associated `Consumer` and `Producer` types for the `VehicleInterface`.
    /// The `VehicleConsumer<R>` struct will implement the `Consumer` trait for the
    /// `VehicleInterface`, with subscribers for the `left_tire` and `exhaust` events.
    /// The `VehicleProducer<R>` struct will implement the `Producer` trait for the
    /// `VehicleInterface`, with publishers for the `left_tire` and `exhaust` events.
    #[cfg(doctest)]
    fn individual_common_macro_with_auto_id() {}

    /// ```
    /// mod my_module {
    ///     use score_com::{interface_common, interface_consumer, interface_producer};
    ///     use score_com::{CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///     interface_common!(Vehicle, "CustomVehicleInterface");
    ///     interface_consumer!(Vehicle, left_tire, Event<Tire>, exhaust, Event<Exhaust>);
    ///     interface_producer!(Vehicle, left_tire, Event<Tire>, exhaust, Event<Exhaust>);
    /// }
    /// ```
    /// This will generate a `VehicleInterface` struct with an `INTERFACE_ID` constant set to
    /// "CustomVehicleInterface".
    /// It will also define associated `Consumer` and `Producer` types for the `VehicleInterface`.
    /// The `VehicleConsumer<R>` struct will implement the `Consumer` trait for the
    /// `VehicleInterface`, with subscribers for the `left_tire` and `exhaust` events.
    /// The `VehicleProducer<R>` struct will implement the `Producer` trait for the
    /// `VehicleInterface`, with publishers for the `left_tire` and `exhaust` events.
    #[cfg(doctest)]
    fn individual_macro_with_custom_id() {}

    /// ```compile_fail
    /// mod my_module {
    ///      use score_com::{interface_common, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///      #[derive(Debug, Reloc)]
    ///      #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///    impl CommData for Tire {
    ///        const ID: &'static str = "Tire";
    ///   }
    ///     #[derive(Debug, Reloc)]
    ///    #[repr(C)]
    ///   pub struct Exhaust {}
    ///   impl CommData for Exhaust {
    ///       const ID: &'static str = "Exhaust";
    ///   }
    ///     interface_common!(Vehicle, "CustomVehicleInterface", {
    ///         left_tire: Event<Tire>,
    ///         exhaust: Event<Exhaust>,
    ///     });
    /// }
    /// ```
    /// This will fail to compile because the `interface_common!` macro does not accept event
    /// definitions and will produce a compile-time error indicating that the macro does not support
    /// event definitions.
    #[cfg(doctest)]
    fn interface_common_macro_with_events() {}

    /// ```compile_fail
    /// mod my_module {
    ///     use score_com::{interface_common, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///     interface_common!(Vehicle, "CustomVehicleInterface", {
    ///         left_tire: Method<Tire>,
    ///         exhaust: Method<Exhaust>,
    ///     });
    /// }
    /// ```
    /// This will fail to compile because the `interface_common!` macro does not accept method
    /// definitions and will produce a compile-time error indicating that the macro does not support
    /// method definitions.
    #[cfg(doctest)]
    fn interface_common_macro_with_methods() {}

    /// ```compile_fail
    /// mod my_module {
    ///     use score_com::{interface_common, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///     interface_common!(Vehicle, "CustomVehicleInterface", {
    ///         left_tire: Field<Tire>,
    ///         exhaust: Field<Exhaust>,
    ///     });
    /// }
    /// ```
    /// This will fail to compile because the `interface_common!` macro does not accept field
    /// definitions and will produce a compile-time error indicating
    /// that the macro does not support field definitions.
    #[cfg(doctest)]
    fn interface_common_macro_with_fields() {}

    /// ```
    /// mod my_module {
    ///     use score_com::{interface_consumer, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///     interface_consumer!(Vehicle, left_tire, Event<Tire>, exhaust, Event<Exhaust>);
    /// }
    /// ```
    /// This will generate a `VehicleConsumer<R>` struct that implements the `Consumer` trait for
    /// the `VehicleInterface`, with subscribers for the `left_tire` and `exhaust` events.
    /// The generated `VehicleConsumer<R>` struct will have fields for each event subscriber, and
    /// the `new` method will initialize these subscribers using
    /// the runtime's `Subscriber::new` method.
    /// The macro will also include error handling to ensure that subscriber creation failures are
    /// properly reported.
    #[cfg(doctest)]
    fn interface_consumer_macro() {}

    /// ```compile_fail
    /// mod my_module {
    ///     use score_com::{interface_consumer, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///     interface_consumer!(Vehicle, left_tire, Method<Tire>, exhaust, Method<Exhaust>);
    /// }
    /// ```
    /// This will fail to compile because the `interface_consumer!` macro does not support Method
    /// definitions and will produce a compile-time error indicating that
    /// Method definitions are not supported.
    #[cfg(doctest)]
    fn interface_consumer_macro_with_Method() {}

    /// ```compile_fail
    /// mod my_module {
    ///     use score_com::{interface_consumer, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///     interface_consumer!(Vehicle, left_tire, Field<Tire>, exhaust, Field<Exhaust>);
    /// }
    /// ```
    /// This will fail to compile because the `interface_consumer!` macro does not support Field
    /// definitions and will produce a compile-time error indicating that
    /// Field definitions are not supported.
    #[cfg(doctest)]
    fn interface_consumer_macro_with_Field() {}

    /// ```compile_fail
    /// mod my_module {
    ///     use score_com::{interface_producer, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///     interface_producer!(Vehicle, left_tire, Event<Tire>, exhaust, Event<Exhaust>);
    /// }
    /// ```
    /// This will generate a `VehicleProducer<R>` struct that implements the `Producer` trait for
    /// the `VehicleInterface`, with publishers for the `left_tire` and `exhaust` events.
    /// So it requires interface_common macro to be called before to generate
    /// the VehicleInterface struct
    /// and implement the Interface trait for it.
    #[cfg(doctest)]
    fn interface_producer_macro() {}

    /// ```compile_fail
    /// mod my_module {
    ///     use score_com::{interface_producer, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///     interface_producer!(Vehicle, left_tire, Method<Tire>, exhaust, Method<Exhaust>);
    /// }
    /// ```
    /// This will fail to compile because the `interface_producer!` macro does not support Method
    /// definitions and will produce a compile-time error indicating that
    /// Method definitions are not supported.
    #[cfg(doctest)]
    fn interface_producer_macro_with_Method() {}

    /// ```compile_fail
    /// mod my_module {
    ///     use score_com::{interface_producer, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///     interface_producer!(Vehicle, left_tire, Field<Tire>, exhaust, Field<Exhaust>);
    /// }
    /// ```
    /// This will fail to compile because the `interface_producer!` macro does not support Field
    /// definitions and will produce a compile-time error indicating that
    /// Field definitions are not supported.
    #[cfg(doctest)]
    fn interface_producer_macro_with_Field() {}
}

#[cfg(test)]
#[allow(dead_code)]
#[allow(unused_imports)]
mod validation_tests {
    #[test]
    fn test_interface_id_auto_generated() {
        mod test_module {
            use score_com::{CommData, ProviderInfo, Publisher, Reloc, Subscriber};

            #[derive(Debug, Reloc)]
            #[repr(C)]
            pub struct Tire {
                pub pressure: f32,
            }
            impl CommData for Tire {
                const ID: &'static str = "Tire";
            }

            crate::interface!(
                interface Vehicle {
                    left_tire: Event<Tire>,
                }
            );

            pub fn validate() {
                // Referencing VehicleInterface by name is itself proof the type was generated;
                // the compiler enforces the name at compile time.
                let interface_id = <VehicleInterface as score_com::Interface>::INTERFACE_ID;
                let expected_id = concat!(module_path!(), "::", "Vehicle");
                assert_eq!(
                    interface_id, expected_id,
                    "Interface ID mismatch for VehicleInterface"
                );
            }
        }
        test_module::validate();
    }

    #[test]
    fn test_consumer_type_generated() {
        mod test_module {
            use score_com::{
                CommData, Consumer, LolaRuntimeImpl as LolaRuntime, ProviderInfo, Publisher, Reloc,
                Subscriber,
            };

            #[derive(Debug, Reloc, Clone)]
            #[repr(C)]
            pub struct Tire {
                pub pressure: f32,
            }
            impl CommData for Tire {
                const ID: &'static str = "Tire";
            }

            #[derive(Debug, Reloc, Clone)]
            #[repr(C)]
            pub struct Exhaust {
                pub temp: f32,
            }
            impl CommData for Exhaust {
                const ID: &'static str = "Exhaust";
            }

            crate::interface!(
                interface Vehicle {
                    left_tire: Event<Tire>,
                    exhaust: Event<Exhaust>,
                }
            );

            pub fn validate() {
                // Referencing VehicleConsumer<LolaRuntime> by name is proof the type was generated.
                // The size check verifies that subscriber fields were generated.
                assert!(
                    std::mem::size_of::<VehicleConsumer<LolaRuntime>>() > 0,
                    "VehicleConsumer should have subscriber fields"
                );
            }
        }
        test_module::validate();
    }

    #[test]
    fn test_producer_type_generated() {
        mod test_module {
            use score_com::{
                CommData, LolaRuntimeImpl as LolaRuntime, Producer, ProviderInfo, Publisher, Reloc,
                Subscriber,
            };

            #[derive(Debug, Reloc, Clone)]
            #[repr(C)]
            pub struct Tire {
                pub pressure: f32,
            }
            impl CommData for Tire {
                const ID: &'static str = "Tire";
            }

            crate::interface!(
                interface Engine {
                    rpm: Event<Tire>,
                }
            );

            pub fn validate() {
                // Referencing EngineProducer<LolaRuntime> by name is proof the type was generated.
                let _ = core::marker::PhantomData::<EngineProducer<LolaRuntime>>;
            }
        }
        test_module::validate();
    }

    #[test]
    fn test_offered_producer_type_generated() {
        mod test_module {
            use score_com::{
                CommData, LolaRuntimeImpl as LolaRuntime, Producer, ProviderInfo, Publisher, Reloc,
                Subscriber,
            };

            #[derive(Debug, Reloc, Clone)]
            #[repr(C)]
            pub struct Tire {
                pub pressure: f32,
            }
            impl CommData for Tire {
                const ID: &'static str = "Tire";
            }

            crate::interface!(
                interface Transmission {
                    gear: Event<Tire>,
                }
            );

            pub fn validate() {
                // Referencing TransmissionOfferedProducer<LolaRuntime> by name is proof the type
                // was generated.
                // The size check verifies that publisher fields were generated.
                assert!(
                    std::mem::size_of::<TransmissionOfferedProducer<LolaRuntime>>() > 0,
                    "TransmissionOfferedProducer should have publisher fields"
                );
            }
        }
        test_module::validate();
    }

    #[test]
    fn test_interface_with_custom_id_validation() {
        mod test_module {
            use score_com::{CommData, Interface, ProviderInfo, Publisher, Reloc, Subscriber};

            #[derive(Debug, Reloc, Clone)]
            #[repr(C)]
            pub struct Tire {
                pub pressure: f32,
            }
            impl CommData for Tire {
                const ID: &'static str = "Tire";
            }

            crate::interface!(
                interface Battery, {
                    Id = "com.example.Battery",
                    voltage: Event<Tire>,
                }
            );

            pub fn validate() {
                // Referencing BatteryInterface by name is proof the type was generated with the
                // correct naming convention; the custom ID is a meaningful runtime assertion.
                let interface_id = <BatteryInterface as Interface>::INTERFACE_ID;
                assert_eq!(
                    interface_id, "com.example.Battery",
                    "Custom interface ID should match provided UID"
                );
            }
        }
        test_module::validate();
    }

    #[test]
    fn test_interface_with_multiple_events_validation() {
        mod test_module {
            use score_com::{
                CommData, Interface, LolaRuntimeImpl as LolaRuntime, ProviderInfo, Publisher,
                Reloc, Subscriber,
            };

            #[derive(Debug, Reloc, Clone)]
            #[repr(C)]
            pub struct Event1Data {
                pub value: i32,
            }
            impl CommData for Event1Data {
                const ID: &'static str = "Event1Data";
            }

            #[derive(Debug, Reloc, Clone)]
            #[repr(C)]
            pub struct Event2Data {
                pub value: f64,
            }
            impl CommData for Event2Data {
                const ID: &'static str = "Event2Data";
            }

            #[derive(Debug, Reloc, Clone)]
            #[repr(C)]
            pub struct Event3Data {
                pub value: bool,
            }
            impl CommData for Event3Data {
                const ID: &'static str = "Event3Data";
            }

            crate::interface!(
                interface MultiEvent {
                    event_one: Event<Event1Data>,
                    event_two: Event<Event2Data>,
                    event_three: Event<Event3Data>,
                }
            );

            pub fn validate() {
                // ID assertion is meaningful at runtime.
                let interface_id = <MultiEventInterface as Interface>::INTERFACE_ID;
                assert_eq!(
                    interface_id,
                    concat!(module_path!(), "::", "MultiEvent"),
                    "Interface ID should be auto-generated from module path and interface name"
                );

                // Referencing Consumer, Producer, and OfferedProducer by name proves all four
                // types were generated, the compiler enforces the names at compile time.
                let _ = core::marker::PhantomData::<MultiEventConsumer<LolaRuntime>>;
                let _ = core::marker::PhantomData::<MultiEventProducer<LolaRuntime>>;
                let _ = core::marker::PhantomData::<MultiEventOfferedProducer<LolaRuntime>>;
            }
        }
        test_module::validate();
    }

    #[test]
    fn test_interface_type_consistency_across_traits() {
        mod test_module {
            use score_com::{
                CommData, Interface, LolaRuntimeImpl as LolaRuntime, ProviderInfo, Publisher,
                Reloc, Subscriber,
            };

            #[derive(Debug, Reloc, Clone)]
            #[repr(C)]
            pub struct Tire {
                pub pressure: f32,
            }
            impl CommData for Tire {
                const ID: &'static str = "Tire";
            }

            crate::interface!(
                interface Suspension {
                    travel: Event<Tire>,
                }
            );

            pub fn validate() {
                // Referencing all four generated types by their expected names is proof of
                // consistent naming, the compiler enforces the names at compile time.
                let _ = core::marker::PhantomData::<SuspensionInterface>;
                let _ = core::marker::PhantomData::<SuspensionConsumer<LolaRuntime>>;
                let _ = core::marker::PhantomData::<SuspensionProducer<LolaRuntime>>;
                let _ = core::marker::PhantomData::<SuspensionOfferedProducer<LolaRuntime>>;

                let interface_id = <SuspensionInterface as Interface>::INTERFACE_ID;
                assert_eq!(
                    interface_id,
                    concat!(module_path!(), "::", "Suspension"),
                    "Interface ID should be auto-generated from module path and interface name"
                );
            }
        }
        test_module::validate();
    }

    #[test]
    fn test_interface_naming_convention_validation() {
        mod test_module {
            use score_com::{
                CommData, LolaRuntimeImpl as LolaRuntime, ProviderInfo, Publisher, Reloc,
                Subscriber,
            };

            #[derive(Debug, Reloc, Clone)]
            #[repr(C)]
            pub struct Data {
                pub value: u32,
            }
            impl CommData for Data {
                const ID: &'static str = "Data";
            }

            crate::interface!(
                interface ABS {
                    status: Event<Data>,
                }
            );

            pub fn validate() {
                // Referencing each generated type by its expected name is itself the proof of
                // correct naming conventions, the compiler enforces the names at compile time.
                // Pattern: {Name}Interface, {Name}Consumer, {Name}Producer, {Name}OfferedProducer
                let _ = core::marker::PhantomData::<ABSInterface>;
                let _ = core::marker::PhantomData::<ABSConsumer<LolaRuntime>>;
                let _ = core::marker::PhantomData::<ABSProducer<LolaRuntime>>;
                let _ = core::marker::PhantomData::<ABSOfferedProducer<LolaRuntime>>;
            }
        }
        test_module::validate();
    }
}
