' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************
@startuml safety_sentinel_binding_independent_design
title "Binding Independent Static Architecture"

package "Binding Independent" as binding_independent <<component>> {
  component "Service Discovery" as binding_independent_service_discovery <<unit>> 
  component "Mocks" as binding_independent_mocks <<unit>> 
  component "Runtime" as binding_independent_runtime <<unit>> 

  package "SkeletonAndServiceElements" as binding_independent_skeleton_and_service_elements <<unit>>

  package "ProxyAndServiceElements" as binding_independent_proxy_and_service_elements <<unit>>

  package "GenericSkeletonAndServiceElements" as binding_independent_generic_skeleton_and_service_elements <<unit>>

  package "GenericProxyAndServiceElements" as binding_independent_generic_proxy_and_service_elements <<unit>>
}

@enduml
