# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

module(name = "root", version = "0.0.1")
bazel_dep(name = "rules_cc", version = "0.2.17")
single_version_override(module_name = "rules_cc", version = "0.2.18")
# single_version_override(module_name = "rules_cc", version = "9.9.9")  <- commented, must be ignored
