/********************************************************************************
 * Copyright (c) 2025 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-License-Identifier: Apache-2.0
 ********************************************************************************/

// This file demonstrate the usage of consumer field APIs, which are generated for the VehicleFieldInterface.

// Notes: we are creating consumer instance specific for field here but this is just for demonstration purpose,
// for same consumer instance method / event/ field can be subscribed as per subscribe interface.

// All the functions and types in this file are just for demonstration purpose,
// as this are not part of any callable because of that unused warning is suppressed for this file.

use score_com::{
    Builder, FindServiceSpecifier, InstanceSpecifier, Interface, Runtime, SampleContainer,
    ServiceDiscovery, Subscriber, Subscription,
};

use com_api_gen::{Tire, VehicleFieldInterface};

#[allow(dead_code)]
type VehicleFieldConsumer<R> = <VehicleFieldInterface as Interface>::Consumer<R>;

// create the consumer.
#[allow(dead_code)]
fn create_consumer_field<R: Runtime>(
    runtime: &R,
    service_id: InstanceSpecifier,
) -> VehicleFieldConsumer<R> {
    let consumer_discovery =
        runtime.find_service::<VehicleFieldInterface>(FindServiceSpecifier::Specific(service_id));
    let available_service_instances = consumer_discovery
        .get_available_instances()
        .expect("Failed to get available service instances");

    // Select service instance at specific handle_index
    let handle_index = 0; // or any index you need from vector of instances
    let consumer_builder = available_service_instances
        .into_iter()
        .nth(handle_index)
        .expect("Failed to get consumer builder at specified handle index");

    consumer_builder
        .build()
        .expect("Failed to build consumer instance")
}

// Function to demonstrate the usage of the consumer to get and set fields,
// and subscribe to field update notifications.
//
// Field get/set are now fully async via the MethodCaller-based wrappers generated by the
// interface! macro. They live on the consumer struct as separate fields (`{name}_get`,
// `{name}_set`) and are independent of subscribe() - they remain usable before and after.
//
// Because subscribe() takes `left_tire` by value, extract the callers before subscribing
// if both are needed in the same async context.
#[allow(dead_code)]
async fn consumer_processing_field<R: Runtime>(consumer: VehicleFieldConsumer<R>) {
    // Async get via the generated get_left_tire() wrapper.
    // Uses MethodCaller<(), Tire> under the hood - reuses Method infrastructure.
    match consumer.get_left_tire().await {
        Ok(result) => println!("Current tire pressure (async get): {:?}", *result),
        Err(e) => eprintln!("Failed to get tire pressure: {:?}", e),
    }

    // Async set via the generated set_left_tire(val) wrapper.
    // Uses MethodCaller<(Tire,), Tire> under the hood - reuses Method infrastructure.
    match consumer.set_left_tire(Tire { pressure: 35.0 }).await {
        Ok(result) => println!("Confirmed tire pressure after set: {:?}", *result),
        Err(e) => eprintln!("Failed to set tire pressure: {:?}", e),
    }

    // Subscribe to the field to receive update notifications (field value changes).
    // Note: subscribe() takes `left_tire` by value. The get/set callers are separate
    // struct fields so they are not consumed here, but the consumer is partially moved.
    let subscription = consumer
        .left_tire
        .subscribe(3)
        .expect("Failed to subscribe to field");

    // Poll for updates (non-blocking)
    let mut sample_buf = SampleContainer::new(3);
    match subscription.try_receive(&mut sample_buf, 1) {
        Ok(n) if n > 0 => {
            while let Some(sample) = sample_buf.pop_front() {
                println!("Updated tire pressure: {:?}", *sample);
            }
        }
        _ => println!("No new tire pressure updates available"),
    }

    // subscription is automatically unsubscribed when dropped
}
