' *******************************************************************************
' Copyright (c) {year} Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

!include fta_metamodel.puml

$FailureMode("Callback invoked with wrong data", "Communication.CallbackInvokedWithWrongData")

$OrGate("Gate1", "Communication.CallbackInvokedWithWrongData")
$IntermediateEvent("Manipulated received data", "Event1", "Gate1")
$OrGate("Gate4", "Event1")
$IntermediateEvent("Dangling data", "Event6", "Gate4")
$RootCause("PTR dangling", "PtrDangling", "Event6")
$RootCause("Callback dangling", "CallbackDangling", "Event6")
$RootCause("Actively manipulate by programm parts", "ActivelyManipulateByProgrammParts", "Gate4")
$IntermediateEvent("Data from wrong sample instance", "Event3", "Gate1")
$OrGate("Gate2", "Event3")
$IntermediateEvent("LookUp wrong Event in same instance", "Event12", "Gate2")
$RootCause("EventFqId wrongly constructed", "EventfqidWronglyConstructed", "Event12")
$IntermediateEvent("LookUp correct event in wrong instance", "Event11", "Gate2")
$IntermediateEvent("Wrong Find-Service", "Event13", "Event11")
$TransferInGate("Transfer1", "Event13")
$IntermediateEvent("Wrong order of sample data", "Event4", "Gate1")
$OrGate("Gate3", "Event4")
$RootCause("Ordering wrong", "OrderingWrong", "Gate3")
$IntermediateEvent("Timestamps can be wrong", "Event8", "Gate3")
$RootCause("Slot allocation synchronisation wrong", "SlotAllocationSynchronisationWrongTimestamp", "Event8")
$IntermediateEvent("Wrong state", "Event9", "Gate3")
$RootCause("Slot allocation synchronisation wrong", "SlotAllocationSynchronisationWrongState", "Event9")
$IntermediateEvent("Repeated data", "Event2", "Gate1")
$IntermediateEvent("Wrong order of sample", "Event5", "Event2")
$TransferInGate("Transfer2", "Event5")

@enduml
