' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************
@startuml

!include fta_metamodel.puml

$TopEvent("Receive handler invoked multiple times", "Communication.ReceiveHandlerInvokedMultipleTimes")

$OrGate("Gate1", "Communication.ReceiveHandlerInvokedMultipleTimes")
$BasicEvent("Notification transport delivers duplicated notifications", "Communication.DuplicatedNotificationDeliveredByTransport", "Gate1")
$IntermediateEvent("Handler is registered more than once", "Event1", "Gate1")
$OrGate("Gate2", "Event1")
$BasicEvent("Previous receive handler registration is not replaced", "Communication.PreviousReceiveHandlerRegistrationNotReplaced", "Gate2")
$BasicEvent("Receive handler registration is repeated on re-subscription", "Communication.ReceiveHandlerRegistrationRepeatedOnResubscription", "Gate2")
$IntermediateEvent("Dispatch multiplies handler invocations", "Event2", "Gate1")
$OrGate("Gate3", "Event2")
$BasicEvent("Queued notifications are not deduplicated before dispatch", "Communication.NotificationsNotDeduplicatedByDispatch", "Gate3")
$BasicEvent("Same receive handler entered concurrently by the local notification thread pool", "Communication.ReceiveHandlerInvokedConcurrentlyByWorkerThreads", "Gate3")

@enduml
