' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************
@startuml

!include fta_metamodel.puml

$TopEvent("Receive handler invoked without event notification", "Communication.ReceiveHandlerInvokedWithoutEventNotification")

$OrGate("Gate1", "Communication.ReceiveHandlerInvokedWithoutEventNotification")
$BasicEvent("Notification transport delivers an incorrect notification", "Communication.IncorrectNotificationDeliveredByTransport", "Gate1")
$IntermediateEvent("Receive handler invoked with wrong event", "Event1", "Gate1")
$TransferInGate("Transfer1", "Event1")
$IntermediateEvent("Handler is invoked although it is no longer registered", "Event2", "Gate1")
$OrGate("Gate2", "Event2")
$BasicEvent("Receive handler is not removed on unregistration", "Communication.ReceiveHandlerNotRemovedOnUnregistration", "Gate2")
$IntermediateEvent("Does not implicit remove receive handler", "Event3", "Gate2")
$TransferInGate("Transfer2", "Event3")
$BasicEvent("Skeleton emits a notification without an event update", "Communication.NotificationSentWithoutEventUpdate", "Gate1")

@enduml
