@startuml

namespace mw_com {
  namespace lola_binding {
    interface "LolaSkeletonForImplSkeletonInterface" as lola_skeleton_for_impl_skeleton_interface <<interface>> {
        PrepareOffer()
        PrepareStopOffer()
        VerifyAllMethodHandlersRegistered()
    }
  }
}

@enduml
