' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************
@startuml lola_proxy_interfaces
title "Lola Proxy Interfaces"

package "Lola Binding" as lola_binding  <<component>> {
  package "ProxyAndServiceElements" as lola_proxy_and_service_elements <<component>> {
    component "Proxy" as lola_proxy <<unit>> 
    component "ProxyEvent" as lola_proxy_event <<unit>> 
    component "ProxyMethod" as lola_proxy_method <<unit>> 
  }
} 

interface "LolaProxyForLolaProxyEventInterface" as lola_proxy_for_lola_proxy_event_interface <<interface>>
lola_proxy_event --( lola_proxy_for_lola_proxy_event_interface
lola_proxy -- lola_proxy_for_lola_proxy_event_interface

interface "LolaProxyForLolaProxyMethodInterface" as lola_proxy_for_lola_proxy_method_interface <<interface>>
lola_proxy_method --( lola_proxy_for_lola_proxy_method_interface
lola_proxy -- lola_proxy_for_lola_proxy_method_interface

interface "LolaProxyMethodForLolaProxyInterface" as lola_proxy_method_for_lola_proxy_interface <<interface>>
lola_proxy --( lola_proxy_method_for_lola_proxy_interface
lola_proxy_method -- lola_proxy_method_for_lola_proxy_interface

@enduml
